### ISSUE TITLE
[Security]: Exposure of Sensitive Information in simple-get

### ISSUE THREAD

**Issue by nbouvrette** [netlify/next-runtime#1176]
### Summary

Exposure of Sensitive Information in simple-get - https://github.com/advisories/GHSA-wpg7-2c88-r8xv

### Steps to reproduce

1. Run `npm audit fix`

```sh
# npm audit report

simple-get  <4.0.1
Severity: high
Exposure of Sensitive Information in simple-get - https://github.com/advisories/GHSA-wpg7-2c88-r8xv
fix available via `npm audit fix --force`
Will install @netlify/plugin-nextjs@3.9.2, which is a breaking change
node_modules/simple-get
  prebuild-install  <=6.1.4
  Depends on vulnerable versions of simple-get
  node_modules/prebuild-install
    sharp  0.18.3 - 0.29.2
    Depends on vulnerable versions of prebuild-install
    Depends on vulnerable versions of simple-get
    node_modules/sharp
      ipx  <=0.3.1 || 0.6.1 - 0.7.2
      Depends on vulnerable versions of sharp
      node_modules/ipx
        @netlify/ipx  *
        Depends on vulnerable versions of ipx
        node_modules/@netlify/ipx
          @netlify/plugin-nextjs  >=4.0.0-beta.1
          Depends on vulnerable versions of @netlify/ipx
          node_modules/@netlify/plugin-nextjs

6 high severity vulnerabilities
```

### Plugin version

3.9.2

### More information about your build

- [ ] I am building using the CLI
- [ ] I am building using file-based configuration (`netlify.toml`)

### Your netlify.toml file

<details>
  <summary>`netlify.toml`</summary>
  
```toml
# Paste content of your `netlify.toml` file here
```

</details>

### Your public/_redirects file

<details>
  <summary>`_redirects`</summary>
  
```toml
# Paste content of your `_redirects` file here
```

</details>

### Your `next.config.js` file

<details>
  <summary>`next.config.js`</summary>
  
```toml
# Paste content of your `next.config.js` file here. Check there is no private info in there.
```

</details>

### Builds logs (or link to your logs)

<details>
  <summary>Build logs</summary>
  
```
# Paste logs here
```

</details>

### Function logs

<details>
  <summary>Function logs</summary>
  
```
# Paste logs here
```

</details>

### .next JSON files

<details>
  <summary>generated .next JSON files</summary>
  
```
# Paste file contents here. Please check there isn't any private info in them
# You can either build locally, or download the deploy from Netlify by clicking the arrow next to the deploy time.
```

</details>

**Comment by sarahetter** [comment]
Closed as this no longer appears in npm audit
