### ISSUE TITLE
[Bug]: `_redirects` not working with `netlify dev`

### ISSUE THREAD

**Issue by naelkhann** [netlify/next-runtime#1203]
### Summary

The `_redirects` file, which as per the [docs](https://github.com/netlify/netlify-plugin-nextjs/blob/main/docs/redirects-rewrites.md#using-_rewrites-and-_headers-files) should be placed in the `/public/` dir is not evaluated when running your application using `netlify dev`.

When running `netlify dev` locally to run my app, redirects specified in the `_redirects` file worked and were evaluated. Now, they do not work.

### Steps to reproduce

1. Create a `_redirects` file. Add a valid redirect rule (you need a page defined in `pages/` dir so you can redirect). For example:
```
/hello /{your_valid_page_route}
```
2. Ensure your `_redirects` file is inside the `/public` directory.
3. Run your Next js app using netlify-cli `netlify dev`.
4. Navigate to the page `{local_domain}/hello`. The redirect will not work.

### Plugin version

4.2.5

### More information about your build

- [X] I am building using the CLI
- [ ] I am building using file-based configuration (`netlify.toml`)

### What OS are you using?

Mac OS

### Your netlify.toml file

<details>
  <summary>`netlify.toml`</summary>
  
```toml
# Paste content of your `netlify.toml` file here
```

</details>

### Your public/_redirects file

<details>
  <summary>`_redirects`</summary>
  
```toml
# Paste content of your `_redirects` file here
```

</details>

### Your `next.config.js` file

<details>
  <summary>`next.config.js`</summary>
  
```toml
# Paste content of your `next.config.js` file here. Check there is no private info in there.
```

</details>

### Builds logs (or link to your logs)

<details>
  <summary>Build logs</summary>
  
```
# Paste logs here
```

</details>

### Function logs

<details>
  <summary>Function logs</summary>
  
```
# Paste logs here
```

</details>

### .next JSON files

<details>
  <summary>generated .next JSON files</summary>
  
```
# Paste file contents here. Please check there isn't any private info in them
# You can either build locally, or download the deploy from Netlify by clicking the arrow next to the deploy time.
```

</details>

**Comment by ajereos-circadence** [comment]
`[[redirects]]` and next config's `async redirects()` also not working for me

**Comment by sarahetter** [comment]
Is this still an issue?

**Comment by sarahetter** [comment]
Closing in favour of #1876
