### ISSUE TITLE
Support using background function

### ISSUE THREAD

**Issue by jbojcic1** [netlify/next-runtime#1247]
Currently the plugin creates a function to handle all next.js pages and apis (for SSR and API routes) but would be great if it would be possible to configure it to use background function instead. That way you'd be able to use next.js api with greater execution limit.
The configuration should be possible per api. So there could be one background function to handle some apis and one normal one for the rest

**Comment by sarahetter** [comment]
Closing - this functionality is now available in v4.27.0 https://github.com/netlify/next-runtime/releases/tag/plugin-nextjs-v4.27.0
