### ISSUE TITLE
Document use of `included_files` for local data in ISR

### ISSUE THREAD

**Issue by ascorbic** [netlify/next-runtime#1256]
It needs to be clearer that when sourcing local data you need to add it to `included_files`. See #1252 for an example.

**Comment by alianza** [comment]
> It needs to be clearer that when sourcing local data you need to add it to `included_files`. See #1252 for an example.

I've created a PR addressing this issue! See: https://github.com/netlify/netlify-plugin-nextjs/pull/1353
