### ISSUE TITLE
Support for on-Demand Revalidation

### ISSUE THREAD

**Issue by kamerat** [netlify/next-runtime#1288]
I'm having issues using the on-demand revalidation when hosted on netlify.
When I[ test it locally](https://nextjs.org/docs/basic-features/data-fetching/incremental-static-regeneration#testing-on-demand-isr-during-development) by doing next build and next start it works. However, when I test it on a build-deploy or live, it does not seem to update the page.

I have validated that the API endpoint in netlify gets run, has the correct data and unstable_revalidate did not break. (in ___netlify-handler function log)

Does on-demand revalidation not work on netlify yet, or am I missing some config?

EDIT: 
### Also discussed in https://github.com/netlify/netlify-plugin-nextjs/discussions/1228

<div type='discussions-op-text'>

<sup>Originally posted by **iankduffy** February 18, 2022</sup>
Hello, NextJS 12.1 has added [On-demand Incremental Static Regeneration](https://nextjs.org/blog/next-12-1#on-demand-incremental-static-regeneration-beta) currently in Beta / Unstable, just wondering if in the future if we are looking to add this to netlify plugin? </div>

**Comment by ascorbic** [comment]
Hi @kamerat 
Currently on-demand revalidation is not supported. It is on our roadmap, but we cannot share a date for support yet.

**Comment by EddyVinck** [comment]
@ascorbic is `unstable_revalidate` unsupported still? I just tried it and it seems to not work, at least.

**Comment by yescine** [comment]
Still to this date with nextjs@12.2.3 `res.revalidate()`, it doesn' t update the page although the revalidate api endpoint handle the request. is this only for the free plan ?

**Comment by ascorbic** [comment]
@yescine @EddyVinck in progress!

**Comment by iurage** [comment]
Hi, any updates on progress for this?

**Comment by orinokai** [comment]
@iurage we are keen to support this as soon as possible and are working toward it as per our roadmap

**Comment by ChazUK** [comment]
Would be good to hear an update on this. It's been a much talked about feature in my team and we're really looking forward to selling this performance benefit to our clients!

**Comment by pm0u** [comment]
Really would like to see this for feature parity with other hosting providers. Any updates on timeline? This is bordering on dealbreaker for us as we have a massive blog that we can't realistically rebuild every time someone finds a typo.

**Comment by ascorbic** [comment]
I'm afraid I can't be any more specific than "this is being worked on". We're waiting on some new platform features that we need for this to work, but I think you'll be pleased with the results.

**Comment by elleryfamilia** [comment]
"this is being worked on"... i mean, seems like a trivial task given that you already support {revalidate: 60}.  If you're concerned about resource use, then just paywall it. It wouldn't be so bad if we also didn't have to wait 60 seconds for revalidation.

**Comment by ascorbic** [comment]
> i mean, seems like a trivial task given that you already support 
Unfortunately it's not. You know what they say are the two hard problems in computer science?

**Comment by theooog** [comment]
@ascorbic Any updates?

**Comment by nickytonline** [comment]
It's actively been looked at at the moment, but I can't provide a timeline yet @theooog.

**Comment by BilegtGG** [comment]
?

**Comment by Raphael2001** [comment]
Hey, any update on that?

**Comment by orinokai** [comment]
@Raphael2001 not too long now 😄

**Comment by ui-jb** [comment]
Hey guys, I'm sure you're sick of people asking, but my team is really excited about this feature.

Are there any updates to this? Or maybe a timeframe? Hopefully I'm not adding too much pressure 😄

**Comment by cbaucom** [comment]
Probably easier to switch to Vercel at this point.

**Comment by osseonews** [comment]
> Probably easier to switch to Vercel at this point.

Guaranteed that right after we switch to Vercel, Netlify will fix this. But growing extremely impatient at the lack of updates on this. Terrible having to manage a NextJS implementation without on demand revalidation.

**Comment by justynspooner** [comment]
@Raphael2001 Our team would also love NextJS On-Demand Revalidation supported on Netlify. Looking forward to seeing this released! Do you have a public roadmap where we can follow along with the progress on this feature?

**Comment by orinokai** [comment]
@justynspooner i'm afraid we don't currently maintain a public roadmap, but please be assured it's a priority and we're working hard to get this shipped

**Comment by tomswork** [comment]
+1 - It would be great to get ongoing updates on this feature, it has major impacts to us in project usages / api limits and bandwidths

**Comment by charkour** [comment]
What are the current pending tasks that need to be completed for this to go live? 

Because this is an open-source plugin, we'd like to contribute to it via a public checklist.

**Comment by caomicc** [comment]
Wondering if there are any updates for this?

**Comment by dev-fredericfox** [comment]
It has been more than a year, can we at least get an update and or ETA?

**Comment by charkour** [comment]
@dev-fredericfox, although it's undocumented, this feature is enabled for Next.js sites on Netlify.

**Comment by dev-fredericfox** [comment]
Dosen't seem to work for me. Did you get it to work on 13 with the app router? 
It works fine locally (Next.js 13 App router), and the webhook returns "ok" when on netlify, but the pages do not refresh.

**Comment by azuxx** [comment]
<img width="1101" alt="Screenshot 2023-09-28 at 16 35 59" src="https://github.com/netlify/next-runtime/assets/16132913/5683567c-ac40-451b-a8c9-e784507e16b8"> Revalidate does not work for me either (using Next 13 with App Router). My current workaround is to redo deploy with the option "Clear cache and retry with latest branch commit".

**Comment by charkour** [comment]
@dev-fredericfox, what is your `revalidate: <ttl>`? For example, my TTL is set to 60 seconds, so even when I run revalidate, my browser will cache the webpage until the TTL is up. Locally, Next.js will immediately update the page (when using `next start`) but with Netlify, it will start the TTL count the moment the page is loaded (not based on when it was built on the server).

**Comment by charkour** [comment]
Revalidate on Next.js 13.3 with the Pages Router works on Netlify. You could email Netlify Support asking if there is anything that needs to be "enabled" on your account, but I don't think that's the case.

**Comment by charkour** [comment]
To test if revalidate is working, you should server-render a timestamp and then mount that in your DOM: "build at <server-rendered-time>". That way you can see when the server revalidated the page. Or, you could open the webpage in a new browser (which hasn't cached the webpage) and it will immediately show the updated page.

**Comment by dev-fredericfox** [comment]
@charkour thanks a lot for your feedback! 

I am using the App router, not pages.

I am revalidating by tag and/or URL. My netlify demo-build is outputting a server generated timestamp, that's how I can tell it is not regenerating the page (the timestamp === the build timestamp, even after post-ing to the revalidate api route). This all works when working locally with `next start`.

I have not set any ttl, maybe that is the issue, what is the default? I have waited more than an hour before trying the revalidation again, but still nothing.

**Comment by charkour** [comment]
@dev-fredericfox, I don't believe there is any default set according to the [Netlify Next.js Docs](https://docs.netlify.com/integrations/frameworks/next-js/incremental-static-regeneration/#use-isr-on-netlify). You could try setting it to 60 seconds. 

I'm not certain Netlify supports the App router On-demand ISR yet.

**Comment by MarcL** [comment]
Hey folks,

We've released an early access version of our new runtime which you can opt-in to via the Netlify app UI or you can manually install it. This should have full support for app router and the various flavours of revalidation for pages and app router. We'll be rolling this out to everyone in the next few weeks but you can try it now.

You'll need Next 13.5+ and Node 18 but it should fix a lot of these issues.

More info here in the docs: [Netlify Next.js](https://docs.netlify.com/frameworks/next-js/overview/)

Let us know if you run into any issues.

Thanks!

**Comment by MarcL** [comment]
Page router ISR and app router revalidation should now be available for everyone in our new `v5` runtime.

Docs and more info here: [Netlify Next.js](https://docs.netlify.com/frameworks/next-js/overview/)

Closing this issue but feel free to raise a new one if you spot any issues.
