### ISSUE TITLE
[Bug]: Image generation broken

### ISSUE THREAD

**Issue by apfelbox** [netlify/next-runtime#1422]
### Summary

Hi,

in one of our staging deployments, all images return a 502.
If I open just the image in a new tab, I get the following error messages:

```
IPX Error: Error: vips__write: write failed\nunix error: No space left on device\n
```

### Steps to reproduce

Not sure how to repoduce. Just open the following URL:
https://blum-lehre-animations--21torr2018.netlify.app/_ipx/w_3840,q_75/%2F_next%2Fstatic%2Fmedia%2Fvertical_teaser_icons.3573aaee.gif?url=%2F_next%2Fstatic%2Fmedia%2Fvertical_teaser_icons.3573aaee.gif&w=3840&q=75

### A link to a reproduction repository

internal repository

### Plugin version

4.9.3

### More information about your build

- [X] I am building using the CLI
- [X] I am building using file-based configuration (`netlify.toml`)

### What OS are you using?

Linux

### Your netlify.toml file

<details>
  <summary>`netlify.toml`</summary>
  
```toml
[build]
    command = "npm run build"
    publish = ".next"

[[plugins]]
    package = "@netlify/plugin-nextjs"
```

</details>

### Your public/_redirects file

<details>
  <summary>`_redirects`</summary>
  
```toml
# Paste content of your `_redirects` file here
```

</details>

### Your `next.config.js` file

<details>
  <summary>`next.config.js`</summary>
  
```toml
const redirectsMap = require("./data/redirects.js");

/** @type {import('next').NextConfig} */
module.exports = {
	reactStrictMode: true,
	webpack (config)
	{
		config.module.rules.push({
			test: /\.svg$/,
			loader: require.resolve('@svgr/webpack'),
		});

		return config;
	},
	/**
	 * Loads the redirects
	 */
	async redirects ()
	{
		return Object.entries(redirectsMap)
			.map(([source, destination]) => {
				return {
					// Be sure to strip trailing slashes in source
					// We have Next.js configured to remove trailing slashes, so they are
					// removed before the redirect is looked up.
					source: source.replace(/\/+$/, ""),
					destination: destination,
					permanent: true,
				};
			});
	},
};

```

</details>

### Builds logs (or link to your logs)

<details>
  <summary>Build logs</summary>
  
```
# Paste logs here
```

</details>

### Function logs

<details>
  <summary>Function logs</summary>
  
not loading, I just get an endless spinner

</details>

### .next JSON files

<details>
  <summary>generated .next JSON files</summary>
  
```
# Paste file contents here. Please check there isn't any private info in them
# You can either build locally, or download the deploy from Netlify by clicking the arrow next to the deploy time.
```

</details>

**Comment by nickytonline** [comment]
I'm curious what the size of the original file is? As the error states, there's no space left and I believe we provide 512 MB of scratch space in `/tmpt`, see https://aws.amazon.com/lambda/faqs/

**Comment by apfelbox** [comment]
Hi,

as this happens for all our images, the answer differs a bit. But most of the images are well below 1MB. 

Is there a way to have some introspection, to debug this further in Netlify?

**Comment by jmeiss** [comment]
Same issue here ( https://get.flui.city/en/budget-participatif/ ) from time to time, randomly, some image doesn't load and we also get that `IPX Error: Error: wbuffer_write: write failed\nunix error: No space left on device\n` error when we open the image on a new tab.

Do you have any workaround while you're looking into fixing this issue?

**Comment by sarahetter** [comment]
Closing in favour of https://github.com/netlify/netlify-ipx/issues/45
