### ISSUE TITLE
Create a cypress project for the middleware demo

### ISSUE THREAD

**Issue by sarahetter** [netlify/next-runtime#1426]
Due to the newest implementation of middleware (as root level instead of nested), we had to remove middleware (and its tests) from our default demo, because it results in clearing out the static page manifest that we still want to test for. 

Since these are mutually exclusive scenarios, we should create a new project to be able to test for middleware.

**Comment by nickytonline** [comment]
I've added it to the backlog

**Comment by nickytonline** [comment]
I think @ascorbic added these back in https://github.com/netlify/netlify-plugin-nextjs/pull/1479?
