### ISSUE TITLE
Auto-enable edge functions if site has edge runtime enabled

### ISSUE THREAD

**Issue by ascorbic** [netlify/next-runtime#1431]
If a user opts-in to edge runtime for SSR or API routes, we should take that as tacit opt-in to use edge functions too. Unlike middleware we won't have any legacy users who started using it before we supported edge functions. It's also meaningless to use it without edge functions. The other option is to fail builds if it's not enabled, but at that point I think we may as well just set the env var ourselves.

**Comment by MarcL** [comment]
Checking with the data and product team on edge function usage before proceeding. 👍
