### ISSUE TITLE
Upgrade minimum Node version to 14 in netlify-plugin-next

### ISSUE THREAD

**Issue by ericapisani** [netlify/next-runtime#1475]
Currently the "engines" property in the plugin's `package.json` is set to node v12.

Given node 12 was EOLed recently, this should be upgraded to 14.

**Comment by ascorbic** [comment]
For frameworks plugins we've been matching the minimum versions in the frameworks themselves. Last time I checked, Next.js still supports 12, but hopefully that will change soon. Gatsby moved to 14 last year, which is why we can require that.

**Comment by charkour** [comment]
With Next v13, the minimum node version is v14: [Docs](https://nextjs.org/docs/upgrading#v13-summary)

**Comment by taty2010** [comment]
Will need to hold off on updating since Next v12 still has node 12 as the minimum.

**Comment by serhalp** [comment]
Superseded by v5.
