### ISSUE TITLE
Can you/How to use Edge-Functions with Next?

### ISSUE THREAD

**Issue by maxeth** [netlify/next-runtime#1577]
Hello,
I was just reading a Netlify Blog post related to Next.js on the edge that stated one could achieve everything Next's middleware do with Netlify Edge-Functions, which sounds to me like you could use Edge-Functions with a Next build.

I tried it out and it works perfectly fine in dev with ```netlify dev```, however, deploys on Netlify fail as building with ```next build``` fails with numerous errors because Next obviously doesn't know what to do with all the Deno imports:

```
Type error: Cannot find module 'https://edge.netlify.com' or its corresponding type declarations.
import type { Context } from "https://edge.netlify.com";
```

Is there some specific way to build a Next app with netlify Edge-Functions? Or is one limited to using Next's built-in middleware?

I couldn't find anything about this in the docs, and unfortunately Next's middleware cannot be used to return JSON like Edge-Functions, which I need for my use-case.

**Comment by ericapisani** [comment]
Hi @maxeth !

Based on my understanding of your question/issue (which might be incorrect so apologies if this doesn't immediately clear things up for you), you're trying to build a standard Next application that includes edge functions as well as Next.js middleware that might have a project structure similar to our `middleware` demo that we have included in this repository [here](https://github.com/netlify/next-runtime/tree/main/demos/middleware)

Regarding the middleware file - you would write the middleware file as you normally would in any Next app (either in Javascript or Typescript, can take a look at the link above as a reference if needed), and running `next build` should work as expected. However, as you're noting, the middleware file isn't changed into an edge function in local development unless run with the Netlify CLI via `netlify dev`.

The `runtime` will bundle that middleware file as an edge function as part of the build/deploy process if you're using the Netlify CLI or importing the project via Github (or other source control).

If the above didn't help clarify things or resolve your issue, could you provide a minimal repro project of what you're trying achieve?

**Comment by maxeth** [comment]
Right, I was trying to use normal Netlify edge functions instead of the ```middleware``` file with a Next build because I wanted to return pure JSON responses on the edge, which Next.js middleware does not support.

I checked out the repo you linked, but it only uses ```middleware.ts``` and not "classic" edge functions, so I cannot just return JSON responses if I'm not mixing something up. 

If I understand corretly, Netlify supports Next's Edge API routes via ```NEXT_USE_NETLIFY_EDGE=true```, but some articles like this one:  https://www.netlify.com/blog/deploy-nextjs-12-2 state that one can use Netlify edge functions with Next.js instead of Next's Edge API routes for better performance

> The API for Netlify Edge Functions is very similar to Edge API Routes, but they don't have the additional overhead of the Next runtime, meaning that in most cases Netlify Edge Functions will have lower latency. They also give you access to thousands of Deno libraries. [...]

And I'm just wondering how to do that as my Next builds fail with the ```netlify/edge-functions``` setup.

**Comment by ericapisani** [comment]
Ah ok, thanks for the clarification.

This is a very lightweight example, but I put together a quick demo [here](https://github.com/netlify/next-runtime/pull/1586) that returns a JSON response when you visit the home page rather than the HTML that's located in `pages/index.js`. 

I confirmed that this works using `netlify dev`, `netlify deploy` and `npm run build` (which invokes `next build`). Just a note that the edge function won't build as part of `npm run build` since it will only build the next site (no netlify edge functions).

Hopefully something in that demo will help you get your site up and running, but otherwise without seeing your project's current set up (or a sample project if you can't provide the one you're working with) that reproduces the error you mentioned above, I'm afraid I'll just be guessing as to what might be the issue and suggesting various things that may or may not work. 😅

**Comment by maxeth** [comment]
Thank you very much, I got it working by not typing ```context``` like you did: 

```export default (req: Request, context: any) => context.json({firstName: "Louise", lastName: "Belcher"});```

When I try do ```import type { Context } from "https://edge.netlify.com";```
to type ```context``` correctly, the build fails with importing errors mentioned previously. 

But I guess setting ```context: any``` works for now :)
