### ISSUE TITLE
Update Next.js logo in README banner

### ISSUE THREAD

**Issue by ascorbic** [netlify/next-runtime#1593]
The Next.js logo has been updated, so we need to update the one in the package READMEs.

Current banner:

![netlify + next.js](https://github.com/netlify/next-runtime/raw/main/next-on-netlify.png)

Next.js brand assets: 

https://vercel.com/design/brands#next-js

**Comment by iKristy** [comment]
Readme image ready:

![next-js-runtime](https://user-images.githubusercontent.com/7912948/188728656-06b0c481-53b9-4623-8d9f-0b25f0cb0406.png)

[Link in Figma →](https://www.figma.com/file/K7CsSUlUaQNtYM2REibeXV/Repo-README-img-template?node-id=1216%3A226)
