### ISSUE TITLE
[Chore]: Consolidate demo sites

### ISSUE THREAD

**Issue by orinokai** [netlify/next-runtime#1643]
[This requirement](https://github.com/netlify/next-runtime/issues/1552) for testing disabling of edge functions would necessitate another demo site and another Cypress run.

I had a look at consolidating some of the existing demo sites and cypress runs. Unfortunately, I found https://github.com/netlify/next-runtime/issues/1426 so it looks like the `middleware` demo needs to remain separate.

Other than that, I propose:
- [ ] remove `custom-routes` demo because the rewrite/redirect functionality in here is already demonstrated in `default` and this site is not tested with Cypress
- [ ] remove `next-with-edge-functions` demo because this is already tested implicitly with the functionality in `middleware` and this site is not tested with Cypress
- [ ] remove `next-i18next` demo because the i18n functionality is already tested in `static-root` and this site is not tested with Cypress
- [ ] rename `static-root` to `i18n` because it only seems to demo/test i18n functionality (unless I'm missing something... what does static root mean?)

**Comment by ascorbic** [comment]
The `custom-routes` demo is mainly testing the redirects, rewrites and headers. It's one that's taken from the next.js monorepo's own e2e tests.  I'm using it for the edge router dev. We might want to turn it off for deploy previews and just enable it on that branch. 

The `static-root` one is testing having a static file as `/`, but that can probably be either removed or merged with something else.

**Comment by ascorbic** [comment]
I think we might still want to move the middleware demo into the default demo. The static manifest should be testable with unit tests.

**Comment by sarahetter** [comment]
> remove next-i18next demo because the i18n functionality is already tested in static-root and this site is not tested with Cypress

The first part of this is incorrect (static-root does not use the `"next-i18next"` dependency in package.json, or have a `demos/next-i18next/next-i18next.config.js` file.

**Comment by sarahetter** [comment]
Closing as duplicate https://github.com/netlify/pod-ecosystem-frameworks/issues/456
