### ISSUE TITLE
Site Deploy Fails Using Yarn 2 PnP

### ISSUE THREAD

**Issue by cravend** [netlify/next-runtime#169]
**Describe the bug**
I recently activated Yarn PnP on my site. However, this is causing the `validateNextUsage` to fail. Switching back to the traditional `node_modules` fixes the issue.

**To Reproduce**
- Create a site using Yarn 2 PnP
- Install Next and deploy to Netlify

**Expected behavior**
Site deploys properly.

**Versions**
- Next.js: 10.0.9
- plugin (if installed at fixed version): 3.0.3

**Comment by denanceapp** [comment]
Any updates on this?

**Comment by Aaron-Storm** [comment]
I had the same issue. I "fixed" it too by setting `nodeLinker` to `"node-modules"` in yarnrc.yml.
But then no pnp support.

**Comment by Levino** [comment]
Just adding "berry" as a keyword here. Should be addressed asap.

**Comment by cravend** [comment]
I've been doing some research on this but haven't had much luck on finding a solution. I did find this issue on Yarn 2's repo that seems to be what we're running into here: https://github.com/yarnpkg/berry/issues/1467

Is there a way for me to locally test this sort of thing? It's a pretty specific issue and I'm not really sure how to get started with it, and I don't see any tests that relate to `validateNextUsage`.

**Comment by electrolyte-orb** [comment]
Is Yarn v2 or v3 used here?
