### ISSUE TITLE
[Bug]: Cannot find module 'next/dist/build/analysis/extract-const-value'

### ISSUE THREAD

**Issue by stwilz** [netlify/next-runtime#1690]
### Summary

Hey there,

We just ran a deploy after the latest plugin release and we are getting the following issue.

Error: Cannot find module 'next/dist/build/analysis/extract-const-value'
Require stack:

/opt/build/repo/web/.netlify/plugins/node_modules/@netlify/plugin-nextjs/lib/helpers/analysis.js
/opt/build/repo/web/.netlify/plugins/node_modules/@netlify/plugin-nextjs/lib/helpers/functions.js
/opt/build/repo/web/.netlify/plugins/node_modules/@netlify/plugin-nextjs/lib/index.js
While loading "@netlify/plugin-nextjs" from Netlify app at Function.Module._resolveFilename (node:internal/modules/cjs/loader:985:15) at Function.Module._load (node:internal/modules/cjs/loader:833:27) at Module.require (node:internal/modules/cjs/loader:1057:19) at require (node:internal/modules/cjs/helpers:103:18) at Object.<anonymous> (/opt/build/repo/web/.netlify/plugins/node_modules/@netlify/plugin-nextjs/lib/helpers/analysis.js:28:31) at Module._compile (node:internal/modules/cjs/loader:1155:14) at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10) at Module.load (node:internal/modules/cjs/loader:1033:32) at Function.Module._load (node:internal/modules/cjs/loader:868:12) at Module.require (node:internal/modules/cjs/loader:1057:19)

Error properties: { code: 'MODULE_NOT_FOUND' }

### Steps to reproduce

1. Trigger Build

### Next Runtime version

4.27.0

### More information about your build

- [ ] I am building using the CLI
- [ ] I am building using file-based configuration (`netlify.toml`)

### Your netlify.toml file

[build]
base = "/web/"
publish = ".next"
command = "yarn build"

### Your `next.config.js` file

// const { withSentryConfig } = require('@sentry/nextjs')

/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  images: {
    domains: ['cdn.sanity.io'],
    deviceSizes: [768, 1280, 1440, 1700],
    imageSizes: [45, 375, 710],
  },
  redirects: async () => [
    {
      source: '/',
      has: [
        {
          type: 'cookie',
          key: 'centreSlug',
          value: '(?<centreSlug>.*)',
        },
      ],
      destination: '/:centreSlug',
      permanent: false,
    },
    {
      source: '/',
      destination: '/intro',
      permanent: false,
    },
  ],
}
module.exports = nextConfig

### Builds logs (or link to your logs)

<details>
  <summary>Build logs</summary>

```
# Paste logs here
```

</details>

### Function logs

<details>
  <summary>Function logs</summary>

```
# Paste logs here
```

</details>

### .next JSON files

<details>
  <summary>generated .next JSON files</summary>

```
# Paste file contents here. Please check there isn't any private info in them
# You can either build locally, or download the deploy from Netlify by clicking the arrow next to the deploy time.
```

</details>

**Comment by gfirem** [comment]
It's happening in my project too. Any help is welcome

**Comment by stwilz** [comment]
@gfirem I've managed to resolve this by upgrading our node packages. We are now using next 12.3.1 + react 18.2.0 and builds are resuming.

**Comment by jamesfromonline** [comment]
> @gfirem I've managed to resolve this by upgrading our node packages. We are now using next 12.3.1 + react 18.2.0 and builds are resuming.

this worked for me as well. thanks!

**Comment by GainorB** [comment]
> 

This also worked for me!

**Comment by GainorB** [comment]
> @gfirem I've managed to resolve this by upgrading our node packages. We are now using next 12.3.1 + react 18.2.0 and builds are resuming.

this also worked for me!

**Comment by Kimbyungkwan** [comment]
only updated "nextjs" and it worked for me , next 11.1.0(😅) -> 12.3.1

**Comment by marika-jane** [comment]
Thanks for this! I am using React version 17.0.2, and only updating Next from 12.1.0 to 12.3.1 has solved it for me! 🥳

**Comment by ascorbic** [comment]
Thanks for the report. The workaround is to upgrade Next.js, but I will put out a fix to work wiht older versions today.
