### ISSUE TITLE
[Bug]: Cache Busting broken when using middleware

### ISSUE THREAD

**Issue by Joroze** [netlify/next-runtime#1706]
### Summary

https://answers.netlify.com/t/netlify-cache-busting-broken-with-nextjs-middleware/77439

I reported this issue on the Netlify forums, but I suppose I should raise the concern here as it may be related to the NextJS runtime plugin.

> Netlify Site name: resplendent-frangollo-dfdb69
> Netlify Site ID: f5112980-d17a-4d3a-afb4-d41e60d55813
> 
> I’m using the latest version of Netlify’s NextJS plugin & a simple middleware that runs in general.
> 
> I’m noticing that requests return with a 200 response, when I believe they should return 304 (according to how Netlify handles cache busting?)
> 
> Screenshot provided:
> ![image](https://user-images.githubusercontent.com/1338914/197414464-8af48051-07b8-4984-9a5a-76973ef93d80.png)
> 

### Steps to reproduce

PR with reproduction based off a Netlify starter template: [Test caching by Joroze · Pull Request #2 · Joroze/next-netlify-starter-nextauth · GitHub](https://github.com/Joroze/next-netlify-starter-nextauth/pull/2)

- As you see, all I did was add a middleware file

Branch deployment URL in question: [https://deploy-preview-2--resplendent-frangollo-dfdb69.netlify.app/](https://deploy-preview-2--resplendent-frangollo-dfdb69.netlify.app/)

### A link to a reproduction repository

https://github.com/Joroze/next-netlify-starter-nextauth/tree/caching

### Next Runtime version

v4.27.3

### More information about your build

- [ ] I am building using the CLI
- [ ] I am building using file-based configuration (`netlify.toml`)

### What OS are you using?

Mac OS

### Your netlify.toml file

<details>
  <summary>`netlify.toml`</summary>

```toml
[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "netlify-plugin-cypress"
```

</details>

### Your public/_redirects file

<details>
  <summary>`_redirects`</summary>

```toml
# Paste content of your `_redirects` file here
```

</details>

### Your `next.config.js` file

<details>
  <summary>`next.config.js`</summary>

```toml
# Paste content of your `next.config.js` file here. Check there is no private info in there.
```

</details>

### Builds logs (or link to your logs)

<details>
  <summary>Build logs</summary>

```
# Paste logs here
```

</details>

### Function logs

<details>
  <summary>Function logs</summary>

```
# Paste logs here
```

</details>

### .next JSON files

<details>
  <summary>generated .next JSON files</summary>

```
# Paste file contents here. Please check there isn't any private info in them
# You can either build locally, or download the deploy from Netlify by clicking the arrow next to the deploy time.
```

</details>

**Comment by sarahetter** [comment]
Closing as stale
