### ISSUE TITLE
[Bug]: Custom Headers broken with 4.27.0

### ISSUE THREAD

**Issue by aileen** [netlify/next-runtime#1712]
### Summary

We're using custom headers with the `next.config.js` implementation as described [here](https://docs.netlify.com/integrations/frameworks/next-js/overview/#custom-headers) to allow fetching from a Next.js API endpoint from another domain.

Since `4.27.0` no custom headers are provided response. They're still working fine in `4.26.0`

### Steps to reproduce

1. Use custom headers in `next.config.js` with version `4.26.0`
2. See headers working for defined paths
3. Upgrade to `4.27.0`
4. No headers being added

Response headers before `4.27.0`:
![CleanShot 2022-10-24 at 14 56 45](https://user-images.githubusercontent.com/8037602/197543582-cb6d32fa-0a31-4a51-82d1-c1ce0f6c6565.png)

Response headers after `4.27.0`:
![CleanShot 2022-10-24 at 14 59 07](https://user-images.githubusercontent.com/8037602/197543820-ad150088-01dc-490e-9f12-3b8d93f9bd98.png)

### A link to a reproduction repository

Private repo

### Next Runtime version

4.27.0

### More information about your build

- [ ] I am building using the CLI
- [ ] I am building using file-based configuration (`netlify.toml`)

### Your netlify.toml file

<details>
  <summary>`netlify.toml`</summary>

```toml
# Paste content of your `netlify.toml` file here
```

</details>

### Your public/_redirects file

<details>
  <summary>`_redirects`</summary>

```toml
# Paste content of your `_redirects` file here
```

</details>

### Your `next.config.js` file

<details>
  <summary>`next.config.js`</summary>

```toml
const nextConfig = {
    reactStrictMode: true,
    basePath: '/explore',
    trailingSlash: true,
      async headers() {
        return [
        {
            source: '/api/feed',
            headers: [
                {
                    key: 'Access-Control-Allow-Origin',
                    value: '*',
                }
            ],
        },
        {
            source: '/:path*',
            headers: [
                {
                    key: 'X-XSS-Protection',
                    value: '1; mode=block'
                },
                {
                    key: 'X-Content-Type-Options',
                    value: 'nosniff'
                },
                {
                    key: 'Referrer-Policy',
                    value: 'no-referrer-when-downgrade'
                },
                {
                    key: 'Strict-Transport-Security',
                    value: 'max-age=31536000'
                },
                {
                    key: 'Feature-Policy',
                    value: 'accelerometer "none"; camera "none"; geolocation "none"; gyroscope "none"; magnetometer "none"; microphone "none"; payment "none"; usb "none"'
                }
            ]
          }
        ]
      }
}

module.exports = nextConfig
```

</details>

### Builds logs (or link to your logs)

<details>
  <summary>Build logs</summary>

```
# Paste logs here
```

</details>

### Function logs

<details>
  <summary>Function logs</summary>

```
# Paste logs here
```

</details>

### .next JSON files

<details>
  <summary>generated .next JSON files</summary>

```
# Paste file contents here. Please check there isn't any private info in them
# You can either build locally, or download the deploy from Netlify by clicking the arrow next to the deploy time.
```

</details>

**Comment by jqlee85** [comment]
My team is having the same issue, `Set-Cookie` headers are not being set on responses from one of our NextJS API endpoints.
