### ISSUE TITLE
[Bug]: Build dependencies error on v4.27+

### ISSUE THREAD

**Issue by PFJoey** [netlify/next-runtime#1718]
### Summary

Updating to the version v.4.27+ introduces the new API routes on Netlify functions. However this introduces many build errors for our application.

### Steps to reproduce

1. Build project
2. Find errors 

### Next Runtime version

v4.27.0

### More information about your build

- [ ] I am building using the CLI
- [X] I am building using file-based configuration (`netlify.toml`)

### What OS are you using?

Linux

### Your netlify.toml file

<details>
  <summary>`netlify.toml`</summary>

```toml
[build]
command = "npm run build"
functions = "functions"
publish = ".next"

[functions]
included_files = ["templates/mail/*"]

[[plugins]]
package = "@netlify/plugin-nextjs"

[[plugins]]
package = "@commandbar/netlify-plugin-commandbar"

[[plugins]]
package = "@netlify/plugin-lighthouse"

[build.environment]
NEXT_USE_NETLIFY_EDGE = "true"

[dev]
functionsPort = 3031
```

</details>

### Your public/_redirects file

<details>
  <summary>`_redirects`</summary>

```toml
# Paste content of your `_redirects` file here
```

</details>

### Your `next.config.js` file

<details>
  <summary>`next.config.js`</summary>

```toml
const withPWA = require('next-pwa');
const withPlugins = require('next-compose-plugins');
const withTM = require('next-transpile-modules')([
  '@fullcalendar/common',
  '@fullcalendar/react',
  '@fullcalendar/daygrid',
  '@fullcalendar/interaction',
  '@fullcalendar/list',
  '@fullcalendar/timegrid',
  '@fullcalendar/timeline',
  '@fullcalendar/resource-timeline',
  '@fullcalendar/adaptive',
]);
const withBundleAnalyzer = require('@next/bundle-analyzer')({
  enabled: process.env.ANALYZE === 'true',
});

/**
 * @type {import('next').NextConfig}
 */
const nextConfig = {
  swcMinify: true,
  trailingSlash: false,
  env: {
    MAPBOX_API: process.env.MAPBOX_API,
    MUI_X_PRO: process.env.MUI_X_PRO,
    BASE_URL: process.env.BASE_URL,
    FIREBASE_APIKEY: process.env.FIREBASE_APIKEY,
    FIREBASE_APP_ID: process.env.FIREBASE_APP_ID,
    FIREBASE_AUTH_DOMAIN: process.env.FIREBASE_AUTH_DOMAIN,
    FIREBASE_MEASUREMENT_ID: process.env.FIREBASE_MEASUREMENT_ID,
    FIREBASE_MESSAGING_SENDER_ID: process.env.FIREBASE_MESSAGING_SENDER_ID,
    FIREBASE_PROJECT_ID: process.env.FIREBASE_PROJECT_ID,
    FIREBASE_STORAGE_BUCKET: process.env.FIREBASE_STORAGE_BUCKET,
    FIREBASE_VAPID_KEY: process.env.FIREBASE_VAPID_KEY,
    NEXT_PUBLIC_CLERK_FRONTEND_API: process.env.NEXT_PUBLIC_CLERK_FRONTEND_API,
    CLERK_API_KEY: process.env.CLERK_API_KEY,
    BACKEND_FUNCTION_SECRET: process.env.BACKEND_FUNCTION_SECRET,
  },
  reactStrictMode: true,
  experimental: {
    modularizeImports: {
      '@mui/icons-material': {
        transform: '@mui/icons-material/{{member}}',
        preventFullImport: true,
      },
      '@mui/material': {
        transform: '@mui/material/{{member}}',
        preventFullImport: true,
      },
      lodash: {
        transform: 'lodash/{{member}}',
        preventFullImport: true,
      },
    },
  },
  images: {
    domains: ['images.clerk.dev', 'minimal-assets-api-dev.vercel.app'],
  },
};

module.exports = (_phase, { defaultConfig }) => {
  const plugins = [withTM, withBundleAnalyzer];
  const config = plugins.reduce((acc, next) => next(acc), {
    ...nextConfig,
  });
  return config;
};
```

</details>

### Builds logs (or link to your logs)

<details>
  <summary>Build logs</summary>

```

7:59:36 AM:   Dependencies installation error                               
7:59:36 AM: ────────────────────────────────────────────────────────────────
7:59:36 AM: ​
7:59:36 AM:   Error message
7:59:36 AM:   A Netlify Function failed to require one of its dependencies.
7:59:36 AM:   Please make sure it is present in the site's top-level "package.json".
​
7:59:36 AM:   Build failed with 11 errors:
7:59:36 AM:   node_modules/enhanced-resolve/lib/ResolverFactory.js:126:17: ERROR: Could not resolve "pnpapi"
7:59:36 AM:   node_modules/next/dist/compiled/webpack/bundle5.js:143690:25: ERROR: Could not resolve "next/dist/build/webpack/plugins/terser-webpack-plugin"
7:59:36 AM:   node_modules/next/dist/compiled/webpack/bundle5.js:143754:25: ERROR: Could not resolve "pnpapi"
7:59:36 AM:   node_modules/next/dist/compiled/webpack/webpack.js:9:40: ERROR: Could not resolve "webpack5/lib/javascript/BasicEvaluatedExpression"
7:59:36 AM:   node_modules/next/dist/compiled/webpack/webpack.js:11:37: ERROR: Could not resolve "webpack5/lib/ModuleFilenameHelpers"```

</details>


### Function logs

<details>
  <summary>Function logs</summary>

```
7:59:36 AM: ▲ [WARNING] "./static-paths-worker" should be marked as external for use with "require.resolve"
7:59:36 AM:     node_modules/next/dist/server/dev/next-dev-server.js:54:72:
7:59:36 AM:       54 │ ...new _jestWorker.Worker(require.resolve("./static-paths-worker"), {
7:59:36 AM:          ╵                                           ~~~~~~~~~~~~~~~~~~~~~~~
7:59:36 AM: ✘ [ERROR] Could not resolve "webpack5/lib/javascript/BasicEvaluatedExpression"
7:59:36 AM:     node_modules/next/dist/compiled/webpack/webpack.js:9:40:
7:59:36 AM:       9 │ ...ssion: require('webpack5/lib/javascript/BasicEvaluatedExpression'),
7:59:36 AM:         ╵                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
7:59:36 AM:   You can mark the path "webpack5/lib/javascript/BasicEvaluatedExpression" as external to exclude it from the bundle, which will remove this error. You can also surround this "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.
7:59:36 AM: ✘ [ERROR] Could not resolve "webpack5/lib/ModuleFilenameHelpers"
7:59:36 AM:     node_modules/next/dist/compiled/webpack/webpack.js:11:37:
7:59:36 AM:       11 │ ...uleFilenameHelpers: require('webpack5/lib/ModuleFilenameHelpers'),
7:59:36 AM:          ╵                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
7:59:36 AM:   You can mark the path "webpack5/lib/ModuleFilenameHelpers" as external to exclude it from the bundle, which will remove this error. You can also surround this "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.
7:59:36 AM: ✘ [ERROR] Could not resolve "webpack5/lib/node/NodeTargetPlugin"
7:59:36 AM:     node_modules/next/dist/compiled/webpack/webpack.js:13:32:
7:59:36 AM:       13 │ ...  NodeTargetPlugin: require('webpack5/lib/node/NodeTargetPlugin'),
7:59:36 AM:          ╵                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
7:59:36 AM:   You can mark the path "webpack5/lib/node/NodeTargetPlugin" as external to exclude it from the bundle, which will remove this error. You can also surround this "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.
7:59:36 AM: ✘ [ERROR] Could not resolve "webpack5/lib/util/StringXor"
7:59:36 AM:     node_modules/next/dist/compiled/webpack/webpack.js:15:25:
7:59:36 AM:       15 │       StringXor: require('webpack5/lib/util/StringXor'),
7:59:36 AM:          ╵                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
7:59:36 AM:   You can mark the path "webpack5/lib/util/StringXor" as external to exclude it from the bundle, which will remove this error. You can also surround this "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.
7:59:36 AM: ✘ [ERROR] Could not resolve "webpack5/lib/NormalModule"
7:59:36 AM:     node_modules/next/dist/compiled/webpack/webpack.js:17:28:
7:59:36 AM:       17 │       NormalModule: require('webpack5/lib/NormalModule'),
7:59:36 AM:          ╵                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~
7:59:36 AM:   You can mark the path "webpack5/lib/NormalModule" as external to exclude it from the bundle, which will remove this error. You can also surround this "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.
7:59:36 AM: ✘ [ERROR] Could not resolve "webpack5"
7:59:36 AM:     node_modules/next/dist/compiled/webpack/webpack.js:19:23:
7:59:36 AM:       19 │       sources: require('webpack5').sources,
7:59:36 AM:          ╵                        ~~~~~~~~~~
7:59:36 AM:   You can mark the path "webpack5" as external to exclude it from the bundle, which will remove this error. You can also surround this "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.
7:59:36 AM: ▲ [WARNING] "./static-paths-worker" should be marked as external for use with "require.resolve"
7:59:36 AM:     node_modules/next/dist/server/dev/next-dev-server.js:54:72:
7:59:36 AM:       54 │ ...new _jestWorker.Worker(require.resolve("./static-paths-worker"), {
7:59:36 AM:          ╵                                           ~~~~~~~~~~~~~~~~~~~~~~~
7:59:36 AM: ✘ [ERROR] Could not resolve "webpack5/lib/javascript/BasicEvaluatedExpression"
7:59:36 AM:     node_modules/next/dist/compiled/webpack/webpack.js:9:40:
7:59:36 AM:       9 │ ...ssion: require('webpack5/lib/javascript/BasicEvaluatedExpression'),
7:59:36 AM:         ╵                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
7:59:36 AM:   You can mark the path "webpack5/lib/javascript/BasicEvaluatedExpression" as external to exclude it from the bundle, which will remove this error. You can also surround this "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.
7:59:36 AM: ✘ [ERROR] Could not resolve "webpack5/lib/ModuleFilenameHelpers"
7:59:36 AM:     node_modules/next/dist/compiled/webpack/webpack.js:11:37:
7:59:36 AM:       11 │ ...uleFilenameHelpers: require('webpack5/lib/ModuleFilenameHelpers'),
7:59:36 AM:          ╵                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
7:59:36 AM:   You can mark the path "webpack5/lib/ModuleFilenameHelpers" as external to exclude it from the bundle, which will remove this error. You can also surround this "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.
7:59:36 AM: ✘ [ERROR] Could not resolve "webpack5/lib/node/NodeTargetPlugin"
7:59:36 AM:     node_modules/next/dist/compiled/webpack/webpack.js:13:32:
7:59:36 AM:       13 │ ...  NodeTargetPlugin: require('webpack5/lib/node/NodeTargetPlugin'),
7:59:36 AM:          ╵                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
7:59:36 AM:   You can mark the path "webpack5/lib/node/NodeTargetPlugin" as external to exclude it from the bundle, which will remove this error. You can also surround this "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.
7:59:36 AM: ✘ [ERROR] Could not resolve "webpack5/lib/util/StringXor"
7:59:36 AM:     node_modules/next/dist/compiled/webpack/webpack.js:15:25:
7:59:36 AM:       15 │       StringXor: require('webpack5/lib/util/StringXor'),
7:59:36 AM:          ╵                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
7:59:36 AM:   You can mark the path "webpack5/lib/util/StringXor" as external to exclude it from the bundle, which will remove this error. You can also surround this "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.
7:59:36 AM: ✘ [ERROR] Could not resolve "webpack5/lib/NormalModule"
7:59:36 AM:     node_modules/next/dist/compiled/webpack/webpack.js:17:28:
7:59:36 AM:       17 │       NormalModule: require('webpack5/lib/NormalModule'),
7:59:36 AM:          ╵                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~
7:59:36 AM:   You can mark the path "webpack5/lib/NormalModule" as external to exclude it from the bundle, which will remove this error. You can also surround this "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.
7:59:36 AM: ✘ [ERROR] Could not resolve "webpack5"
7:59:36 AM:     node_modules/next/dist/compiled/webpack/webpack.js:19:23:
7:59:36 AM:       19 │       sources: require('webpack5').sources,
7:59:36 AM:          ╵                        ~~~~~~~~~~
7:59:36 AM:   You can mark the path "webpack5" as external to exclude it from the bundle, which will remove this error. You can also surround this "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.
7:59:36 AM: ✘ [ERROR] Could not resolve "pnpapi"
7:59:36 AM:     node_modules/enhanced-resolve/lib/ResolverFactory.js:126:17:
7:59:36 AM:       126 │     return require("pnpapi"); // eslint-disable-line node/no-miss...
7:59:36 AM:           ╵                    ~~~~~~~~
7:59:36 AM:   You can mark the path "pnpapi" as external to exclude it from the bundle, which will remove this error. You can also surround this "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.
7:59:36 AM: ✘ [ERROR] Could not resolve "next/dist/build/webpack/plugins/terser-webpack-plugin"
7:59:36 AM:     node_modules/next/dist/compiled/webpack/bundle5.js:143690:25:
7:59:36 AM:       143690 │ ...= require("next/dist/build/webpack/plugins/terser-webpack-p...
             ╵              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
7:59:36 AM:   You can mark the path "next/dist/build/webpack/plugins/terser-webpack-plugin" as external to exclude it from the bundle, which will remove this error. You can also surround this "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.
7:59:36 AM: ✘ [ERROR] Could not resolve "pnpapi"
7:59:36 AM:     node_modules/next/dist/compiled/webpack/bundle5.js:143754:25:
7:59:36 AM:       143754 │ module.exports = require("pnpapi");
7:59:36 AM:              ╵                          ~~~~~~~~
7:59:36 AM:   You can mark the path "pnpapi" as external to exclude it from the bundle, which will remove this error. You can also surround this "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.
7:59:36 AM: ✘ [ERROR] Could not resolve "pnpapi"
7:59:36 AM:     node_modules/enhanced-resolve/lib/ResolverFactory.js:126:17:
7:59:36 AM:       126 │     return require("pnpapi"); // eslint-disable-line node/no-miss...
7:59:36 AM:           ╵                    ~~~~~~~~
7:59:36 AM:   You can mark the path "pnpapi" as external to exclude it from the bundle, which will remove this error. You can also surround this "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.
7:59:36 AM: ✘ [ERROR] Could not resolve "next/dist/build/webpack/plugins/terser-webpack-plugin"
7:59:36 AM:     node_modules/next/dist/compiled/webpack/bundle5.js:143690:25:
7:59:36 AM:       143690 │ ...= require("next/dist/build/webpack/plugins/terser-webpack-p...
             ╵              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
7:59:36 AM:   You can mark the path "next/dist/build/webpack/plugins/terser-webpack-plugin" as external to exclude it from the bundle, which will remove this error. You can also surround this "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.
7:59:36 AM: ✘ [ERROR] Could not resolve "@swc/core"
7:59:36 AM:     node_modules/terser-webpack-plugin/dist/utils.js:557:22:
7:59:36 AM:       557 │   const swc = require("@swc/core"); // Copy `swc` options
7:59:36 AM:           ╵                       ~~~~~~~~~~~
7:59:36 AM:   You can mark the path "@swc/core" as external to exclude it from the bundle, which will remove this error. You can also surround this "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.
7:59:36 AM: 1 of 60 warnings and 9 of 11 errors shown (disable the message limit with --log-limit=0)
7:59:36 AM: 1 of 60 warnings and 9 of 11 errors shown (disable the message limit with --log-limit=0)```

</details>

### .next JSON files

<details>
  <summary>generated .next JSON files</summary>

```
# Paste file contents here. Please check there isn't any private info in them
# You can either build locally, or download the deploy from Netlify by clicking the arrow next to the deploy time.
```

</details>

**Comment by ascorbic** [comment]
@PFJoey does this mean you solved the problem?

**Comment by PFJoey** [comment]
Yes. Issue was on my end, my bad :-)
