### ISSUE TITLE
Issues with next/image in Next.js 13

### ISSUE THREAD

**Issue by nickytonline** [netlify/next-runtime#1721]
## Description

@ericapisani the next/image tests are failing at the moment. The images seem to display fine, but the tests fail. I'm going to switch them to use next/legacy/image and we can look into why the new component is breaking thing.

_Originally posted by @ascorbic in https://github.com/netlify/next-runtime/issues/1714#issuecomment-1290749247_

**Comment by nickytonline** [comment]
From what I can see it's just the tests timing out sometimes. Here they are passing on the second go.

![CleanShot 2022-10-26 at 16 50 00](https://user-images.githubusercontent.com/833231/198134939-1d7b8cee-7032-4e35-b936-5a17afbbca72.png)

**Comment by ascorbic** [comment]
There might be another issue too: I see from that screenshot that the image that should be broken is being shown. I'm guessing something has changed with remotePatterns allow-listing?

**Comment by ericapisani** [comment]
@ascorbic Yeah, I think it was me who added it to the allow list because it was throwing an exception and causing things to break/not run and I forgot to update the page to remove the comment that it shouldn't be showing. 😕

**Comment by nickytonline** [comment]
I think we can remove it from that page as it throws a 500. We have a broken-image page where we already test a broken image.
