### ISSUE TITLE
[Bug]: Cannot find module 'next/dist/shared/lib/app-router-context.js' with Next.js 13

### ISSUE THREAD

**Issue by antonybudianto** [netlify/next-runtime#1723]
### Summary

Hi, I try to deploy Next.js v13 app to Netflify, the build was success, but the deploy preview url got 500 error, after checking the function, turned there's missing module error.
- Tried next build and start locally, no issue
- I also tried to deploy to Vercel with same branch, it works. ([PR sample](https://github.com/antonybudianto/next-antonybudianto/pull/12))
- I've also run clear cache and redeploy but still got 500. https://deploy-preview-12--antonybudianto.netlify.app/

*Posted log on Function log section

Thank you for your support 🙏🏻 

### Steps to reproduce

1. Clone https://github.com/antonybudianto/next-antonybudianto
2. Checkout to `dev` branch
3. Deploy to netlify
4. Got 500 error

### A link to a reproduction repository

https://github.com/antonybudianto/next-antonybudianto/

### Next Runtime version

4.28.1

### More information about your build

- [ ] I am building using the CLI
- [X] I am building using file-based configuration (`netlify.toml`)

### Your netlify.toml file

[[plugins]]
package = "@netlify/plugin-nextjs"

### Your public/_redirects file

<details>
  <summary>`_redirects`</summary>

```toml
# Paste content of your `_redirects` file here
```

</details>

### Your `next.config.js` file

<details>
  <summary>`next.config.js`</summary>

```js
/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: false,
  swcMinify: true,
  experimental: {
    appDir: true,
  },
};

module.exports = nextConfig;
```

</details>

### Builds logs (or link to your logs)

<details>
  <summary>Build logs</summary>

```
2:00:30 PM: $ yarn build
2:00:30 PM: yarn run v1.22.19
2:00:30 PM: $ next build
2:00:30 PM: warn  - You have enabled experimental feature (appDir) in next.config.js.
2:00:30 PM: warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.
2:00:30 PM: info  - Thank you for testing `appDir` please leave your feedback at https://nextjs.link/app-feedback
2:00:30 PM: warn  - No build cache found. Please configure build caching for faster rebuilds. Read more: https://nextjs.org/docs/messages/no-cache
2:00:30 PM: info  - Creating an optimized production build...
2:00:30 PM: info  - Compiled successfully
2:00:30 PM: info  - Linting and checking validity of types...
2:00:30 PM: info  - Collecting page data...
2:00:30 PM: info  - Generating static pages (0/3)
2:00:30 PM: info  - Generating static pages (3/3)
2:00:30 PM: info  - Finalizing page optimization...
2:00:30 PM: Route (app)                                Size     First Load JS
2:00:30 PM: ─ ○ /                                      0 B                0 B
2:00:30 PM: + First Load JS shared by all              66.5 kB
2:00:30 PM:   ├ chunks/main-app-9fbe7621087549d7.js    64.4 kB
2:00:30 PM:   └ chunks/webpack-151ac98db2ceb433.js     2.03 kB
2:00:30 PM: Route (pages)                              Size     First Load JS
2:00:30 PM: ┌   /_app                                  0 B            80.2 kB
2:00:30 PM: └ ○ /404                                   179 B          80.3 kB
2:00:30 PM: + First Load JS shared by all              84 kB
2:00:30 PM:   ├ chunks/main-aa32f7dd722ddf9b.js        77.3 kB
2:00:30 PM:   ├ chunks/pages/_app-01135c343aba8f60.js  821 B
2:00:30 PM:   ├ chunks/webpack-151ac98db2ceb433.js     2.03 kB
2:00:30 PM:   └ css/863675e8e5f4e4bd.css               3.87 kB
2:00:30 PM: ○  (Static)  automatically rendered as static HTML (uses no initial props)
2:00:30 PM: Done in 15.20s.
2:00:30 PM: ​
2:00:30 PM: (build.command completed in 15.3s)
```

</details>

### Function logs

<details>
  <summary>Function logs</summary>

```
Oct 27, 07:20:58 AM: 432e97cc ERROR  Error: Cannot find module 'next/dist/shared/lib/app-router-context.js'Oct 27, 07:20:58 AM: 432e97cc ERROR  Require stack:Oct 27, 07:20:58 AM: 432e97cc ERROR  - /var/task/.next/server/app/page.jsOct 27, 07:20:58 AM: 432e97cc ERROR  - /var/task/node_modules/next/dist/server/require.jsOct 27, 07:20:58 AM: 432e97cc ERROR  - /var/task/node_modules/next/dist/server/next-server.jsOct 27, 07:20:58 AM: 432e97cc ERROR  - /var/task/.netlify/functions-internal/___netlify-handler/handlerUtils.jsOct 27, 07:20:58 AM: 432e97cc ERROR  - /var/task/.netlify/functions-internal/___netlify-handler/___netlify-handler.jsOct 27, 07:20:58 AM: 432e97cc ERROR  - /var/task/___netlify-handler.jsOct 27, 07:20:58 AM: 432e97cc ERROR  - /var/runtime/index.mjsOct 27, 07:20:58 AM: 432e97cc ERROR      at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
```

</details>

![Uploading Screen Shot 2022-10-27 at 7.29.55 AM.png…]()

### .next JSON files

<details>
  <summary>generated .next JSON files</summary>

```
# Paste file contents here. Please check there isn't any private info in them
# You can either build locally, or download the deploy from Netlify by clicking the arrow next to the deploy time.
```

</details>

**Comment by ascorbic** [comment]
Hi. Next 13 is not currently supported by default on Netlify. Support for the pages dir is in the latest runtime, which will be auto-installed by default later today. Support for app dir is experimental, and will require enabling some options. I'll be sharing details very soon.

**Comment by antonybudianto** [comment]
I see.. also I saw this PR https://github.com/netlify/next-runtime/pull/1638 and tried the alpha release and it works now 😅

**Comment by ascorbic** [comment]
Awesome! I'll have a post with more info soon.

**Comment by antonybudianto** [comment]
By the way, I just noticed that the SPA navigation breaks 😅  but the SSR itself still worked
