### ISSUE TITLE
[Bug]: Advanced Middleware does not work with Next 13.0.1

### ISSUE THREAD

**Issue by orinokai** [netlify/next-runtime#1732]
### Summary

Next 13.0.1 introduces a [breaking change](https://github.com/vercel/next.js/pull/41526/files#diff-c8f268758a032861159a8251548a886cb07a9731b598f3551aae83d29c1186b4R36) that adds a `ResponseCookies` class. This new class uses the deprecated method, `getAll`, which is not implemented in Deno's `fetch` and thus throws a 500 error.

I imagine the solution will be to polyfill the method in the @netlify/next middleware response object.

### Steps to reproduce

1. Clone repro site
2. Run `ntl dev`

### A link to a reproduction repository

https://github.com/orinokai/test-next-adv-middleware

### Next Runtime version

4.28.3

### More information about your build

- [X] I am building using the CLI
- [ ] I am building using file-based configuration (`netlify.toml`)

### What OS are you using?

Mac OS

### Your netlify.toml file

<details>
  <summary>`netlify.toml`</summary>

```toml
# Paste content of your `netlify.toml` file here
```

</details>

### Your public/_redirects file

<details>
  <summary>`_redirects`</summary>

```toml
# Paste content of your `_redirects` file here
```

</details>

### Your `next.config.js` file

<details>
  <summary>`next.config.js`</summary>

```toml
# Paste content of your `next.config.js` file here. Check there is no private info in there.
```

</details>

### Builds logs (or link to your logs)

<details>
  <summary>Build logs</summary>

```
# Paste logs here
```

</details>

### Function logs

<details>
  <summary>Function logs</summary>

```
# Paste logs here
```

</details>

### .next JSON files

<details>
  <summary>generated .next JSON files</summary>

```
# Paste file contents here. Please check there isn't any private info in them
# You can either build locally, or download the deploy from Netlify by clicking the arrow next to the deploy time.
```

</details>

**Comment by SeanMcTernan** [comment]
Hey team, any update on this one?

**Comment by nickytonline** [comment]
It's been prioritized, but work hasn't started on this yet.

**Comment by ascorbic** [comment]
Referring to https://github.com/whatwg/fetch/issues/973, this could be implemented using `headers.entries()`, which returns multiple entries for `set-cookie` if found.
