### ISSUE TITLE
[Bug]: fail build if `output: 'standalone'` config option is set

### ISSUE THREAD

**Issue by jasonbarry** [netlify/next-runtime#1736]
### Summary

Those coming from the docker/k8s world are likely to follow [this guidance from Next.js official docs](https://nextjs.org/docs/deployment#docker-image), which instructs them to clone the `with-docker` example, whose [config](https://github.com/vercel/next.js/blob/canary/examples/with-docker/next.config.js) explicitly uses `output: 'standalone'`: 

```js
module.exports = {
  output: 'standalone',
}
```

> This will create a folder at .next/standalone which can then be deployed on its own without installing node_modules.

> Additionally, a minimal server.js file is also output which can be used instead of next start. This minimal server does not copy the public or .next/static folders by default as these should ideally be handled by a CDN instead, although these folders can be copied to the standalone/public and standalone/.next/static folders manually, after which server.js file will serve these automatically. 

As this relies on an always-running node.js server, it's incompatible with our serverless lyfestyle. 

@ascorbic suggested that rather than changing the site's next.config.js file at build-time, we fail the build and output an error message: 

> I think the most useful then would be for us to detect that setting and fail the build, with an appropriate message

Having this error message will be immensely useful for those coming from Next.js wrapped in docker. 

### Steps to reproduce

1. Clone and deploy the `with-docker` example from Next.js examples

### Next Runtime version

4.28.3

### More information about your build

- [ ] I am building using the CLI
- [ ] I am building using file-based configuration (`netlify.toml`)

### Your `next.config.js` file

<details>
  <summary>`next.config.js`</summary>

```js
module.exports = {
  output: 'standalone',
}
```

</details>

**Comment by serhalp** [comment]
@ascorbic Is this still relevant with v5?

**Comment by ascorbic** [comment]
It won't be, because it's forced to standalone anyway
