### ISSUE TITLE
[Bug]: Next.js v13 crashes after few deploys

### ISSUE THREAD

**Issue by NADESHIKON** [netlify/next-runtime#1742]
### Summary

![image](https://user-images.githubusercontent.com/20222292/200157194-0222b532-03aa-4eda-bdc7-ce69d3968c9f.png)

It was working fine for first few deploys then suddenly this shows up.

### Steps to reproduce

1. Use Next.js on Netlify with next-runtime version ``4.28.4-appdir.0``

### Next Runtime version

4.28.4-appdir.0

### More information about your build

- [ ] I am building using the CLI
- [ ] I am building using file-based configuration (`netlify.toml`)

### Your netlify.toml file

<details>
  <summary>`netlify.toml`</summary>

```toml
# Paste content of your `netlify.toml` file here
```

</details>

### Your public/_redirects file

<details>
  <summary>`_redirects`</summary>

```toml
# Paste content of your `_redirects` file here
```

</details>

### Your `next.config.js` file

<details>
  <summary>`next.config.js`</summary>

```toml
# Paste content of your `next.config.js` file here. Check there is no private info in there.
```

</details>

### Builds logs (or link to your logs)

<details>
  <summary>Build logs</summary>

```
# Paste logs here
```

</details>

### Function logs

<details>
  <summary>Function logs</summary>

```
# Paste logs here
```

</details>

### .next JSON files

<details>
  <summary>generated .next JSON files</summary>

```
# Paste file contents here. Please check there isn't any private info in them
# You can either build locally, or download the deploy from Netlify by clicking the arrow next to the deploy time.
```

</details>

**Comment by ascorbic** [comment]
Hi. Thanks for the report. This seems to be a problem with how we're bundling pnpm dependencies. You should be able to work around it by creating `.npmrc` with the following content:

```ini
public-hoist-pattern[]=*
```
