### ISSUE TITLE
Rewrites are broken on edge middleware

### ISSUE THREAD

**Issue by sarahetter** [netlify/next-runtime#1749]
`NextResponse.rewrite(url)` currently does not work when running middleware on the edge - it's returning  301 Moved Permanently. 
When running on origin, it correctly returns a 200. It also works when using our middleware object in the `@netlify/next` package.

e2e test: `middleware-trailing-slash`

**Comment by ascorbic** [comment]
I'm pretty sure this does work now: https://next-plugin-edge-middleware.netlify.app/shows/rewriteme

**Comment by ericapisani** [comment]
@ascorbic I moved the related e2e test out of the 'disabled-tests' section and there's still some [test failures](https://github.com/netlify/next-runtime/actions/runs/3733224353/jobs/6333761285) so I think there's still something to look at here 😕

**Comment by ascorbic** [comment]
Yeah I should be clearer that while the test that this breaks is in there, it's not the only one that's broken! Most are broken by the other issues with trailing slash support on the edge

**Comment by ericapisani** [comment]
Ah ok, thanks for the clarification. I'll close this one then since you're right, the link that you have in your previous comment shows that what's referenced here is addressed
