### ISSUE TITLE
[Bug]: middleware request.geo object is empty

### ISSUE THREAD

**Issue by jadenguitarman** [netlify/next-runtime#1751]
### Summary

This is my middleware file:

```js
import { NextResponse } from 'next/server';

export const config = {
	matcher: '/'
};

export const middleware = async request => {
	const response = NextResponse.next();
	response.cookies.set(
		'currentCoords',
		`${request.geo.latitude}, ${request.geo.longitude}`
	);
	return response;
};
```

I'd expect that this would set a cookie named `currentCoords` to the coordinates from the `request.geo` object. However, the `request.geo` object doesn't have any coordinate information like [the Next docs says it should](https://nextjs.org/docs/api-reference/next/server). When I `console.log` it, I get the `city` I'm currently in, in the right `region` and `country`, but nothing else.

### Steps to reproduce

1. Create a blank repo with the above middleware.
2. Insert a statement to log the `request.geo` object to the console.
3. Visit a page the middleware will intercept.
4. Observe the logged object, which will not match my expectations above. It's missing coordinate information (which Netlify should have available) and will include the `region` key as specified in [the Next docs](https://nextjs.org/docs/api-reference/next/server) instead of the `subdivision` key from [the Netlify docs](https://docs.netlify.com/edge-functions/api/#netlify-specific-context-object).

### A link to a reproduction repository

https://github.com/jadenguitarman/algolia-next-netlify

Site is live at charleston.netlify.app, site id is `51751fce-133f-4e5b-8cca-fcd5704a9e07`

### Next Runtime version

4.28.5

### More information about your build

- [X] I am building using the CLI
- [ ] I am building using file-based configuration (`netlify.toml`)

### What OS are you using?

Mac OS

### Your `next.config.js` file

<details>
  <summary>`next.config.js`</summary>

```js
/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  swcMinify: true,
}

module.exports = nextConfig

```

</details>

**Comment by nickytonline** [comment]
@jadenguitarman, it should be available now. We're in the process of documenting it, but you can give it a go.

![image](https://user-images.githubusercontent.com/833231/201955875-af5c2fb5-c458-4d28-9ac5-b7ba2cb02c62.png)
