### ISSUE TITLE
Middleware should merge API route response cookies

### ISSUE THREAD

**Issue by ascorbic** [netlify/next-runtime#1797]
Currently, calling `res.cookies.set` in middleware replaces any cookies set by an API route. Instead they should be merged. 

e2e test: `skip-trailing-slash-redirect`

**Comment by taty2010** [comment]
Test: 
https://github.com/netlify/next-runtime/blob/e02c2b7e5555805d499b541feda2dbbf94da4a4f/test/e2e/modified-tests/skip-trailing-slash-redirect/index.test.ts

App:
https://github.com/netlify/next-runtime/blob/e02c2b7e5555805d499b541feda2dbbf94da4a4f/test/e2e/modified-tests/skip-trailing-slash-redirect/app/pages/api/test-cookie.js

https://github.com/netlify/next-runtime/blob/e02c2b7e5555805d499b541feda2dbbf94da4a4f/test/e2e/modified-tests/skip-trailing-slash-redirect/app/middleware.js

**Comment by ascorbic** [comment]
The specific test is [this one](https://github.com/netlify/next-runtime/blob/e02c2b7e5555805d499b541feda2dbbf94da4a4f/test/e2e/modified-tests/skip-trailing-slash-redirect/index.test.ts#L51), which you can enable by setting `RUN_SKIPPED_TESTS`
