### ISSUE TITLE
[Bug]: NextJS 13 - Dynamic API Route Works Locally & on Vercel but not on Netlify

### ISSUE THREAD

**Issue by SeanMcTernan** [netlify/next-runtime#1803]
### Summary

I’m attempting to authorize our SE Swag store with Auth0. The problem is occurring when I click the Login once deployed on Netlify, it seems to be treating the dynamic API route as a page. As a sanity check, I deployed an identical repo (minus Netlify dependencies) to Vercel and it the API route is handled just fine. Similarly, the setup works correctly on LocalHost. 

[Account Deploys](https://app.netlify.com/sites/next-netlifyswag/deploys)
[Repo](https://github.com/Netlify-Moneytronic/next-netlifyswag/tree/add_auth)
[Netlify Deploy](https://add-auth--next-netlifyswag.netlify.app/)
[Vercel Deploy](https://next-swag-vercel-a7l7.vercel.app/)

From the network requests below, you can see that the requests are correctly routing to Auth0 in LocalHost and Vercel, but not Netlify. 

**Local host:**
<img width="1726" alt="LocalHost" src="https://user-images.githubusercontent.com/49627314/203422845-d28ad369-4b5e-448b-9d1d-0302ff4f4af8.png">

**Vercel:**
![Vercel](https://user-images.githubusercontent.com/49627314/203422911-54e1255a-4bec-4f32-8431-7b7ae9481152.png)

**Netlify**
<img width="1726" alt="Netlify" src="https://user-images.githubusercontent.com/49627314/203422989-d7f195d9-274e-4e32-aa3c-fa0ed8539934.png">

I've checked the Environment variables and callback URL's for Auth0 and they are, in fact, correct. For posterity, I am posting them here. 

### Netlify Env Vars
![Base_URL](https://user-images.githubusercontent.com/49627314/203425366-2017e11e-7938-4fed-be79-36d7791f1c87.png)
![Client_ID](https://user-images.githubusercontent.com/49627314/203425373-f5da550e-b29f-4100-8544-e6eca6e79cc4.png)
![Client_Secret](https://user-images.githubusercontent.com/49627314/203425375-3ff8337e-d357-45c0-bed1-66ab89b1bc16.png)
![Issuer_URL](https://user-images.githubusercontent.com/49627314/203425377-27ce6b82-d6e6-45eb-9fc0-e154d6f462c4.png)
![Secret](https://user-images.githubusercontent.com/49627314/203425378-bb7ebead-7e38-4a7f-87af-ec14ca24abda.png)

### Auth0 Config
![Screen Shot 2022-11-22 at 2 26 13 PM](https://user-images.githubusercontent.com/49627314/203425464-d807ae1a-146e-4a72-82a3-701e2e410f38.png)
![Screen Shot 2022-11-22 at 2 26 27 PM](https://user-images.githubusercontent.com/49627314/203425467-abe56e78-b701-4cdc-9eba-2cde419e23e0.png)

Finally, according to the build log, the Route is being recognized as a NextJS dynamic API Route. 
![Screen Shot 2022-11-22 at 2 44 59 PM](https://user-images.githubusercontent.com/49627314/203427535-f93512d9-0094-434e-9d87-b5a14d27d411.png)

### Steps to reproduce

1. Clone the Repo 
2. Request EnvVar file from @SeanMcTernan 
3. Deploy Locally
4. Deploy to Netlify
5. Click Login

### A link to a reproduction repository

https://github.com/Netlify-Moneytronic/next-netlifyswag/tree/add_auth

### Next Runtime version

13.0.1

### More information about your build

- [X] I am building using the CLI
- [X] I am building using file-based configuration (`netlify.toml`)

### What OS are you using?

Mac OS

### Your netlify.toml file

```
# explicit commands for building the site
# and the folder to publish
[build]
command = "yarn build"
publish = ".next"

[build.environment]
# cache Cypress binary in local "node_modules" folder
# so Netlify caches it
CYPRESS_CACHE_FOLDER = "./node_modules/CypressBinary"
# set TERM variable for terminal output
TERM = "xterm"

#[context.production]
#  # Overide the default command so the basic auth headers are not added in production
  command = "yarn build"

[[plugins]]
# runs Cypress tests against the deployed URL
package = "netlify-plugin-cypress"
  [plugins.inputs]
    record = true
```

### Your public/_redirects file

<details>
  <summary>`_redirects`</summary>

```toml
# Paste content of your `_redirects` file here
```

</details>

### Builds logs (or link to your logs)

https://app.netlify.com/sites/next-netlifyswag/deploys/6377e835b9963d0008af7cb1

**Comment by SeanMcTernan** [comment]
UPDATE:

A [branch deploy](https://testing-next12-with-auth--next-netlifyswag.netlify.app/) using Next Version 12 works as expected. The problem seems to be with Netlify and the way it's supporting NextJS 13.

**Comment by SeanMcTernan** [comment]
UPDATE:

A [branch deploy](https://testing-next12-with-auth--next-netlifyswag.netlify.app/) using Next Version 12 works as expected. The problem seems to be with Netlify and the way it's supporting NextJS 13 dynamic API routes.

**Comment by SeanMcTernan** [comment]
Update 2:

While working on the add_auth Branch, I updated the Navbar to handle the links using the Link component rather than the anchor tag:

**Before:**
```
{!user ? (
              <a data-test="login-button" href="/api/auth/login">Login</a>) : (<a data-test="logout-button" href="/api/auth/logout">Logout</a>)}
```

**After**

```
{!user ? (
              <Link data-test="login-button" href="/api/auth/login">Login</Link>) : (<Link data-test="logout-button" href="/api/auth/logout">Logout</Link>)}
```

The behaviour has changed slightly. The Login/Logout links no longer take you to an API page, rather nothing happens when you click the links. It appears to have trouble parsing the `!user` logic. 

Once again, this behaviour is only shown on Netlify, local host and Vercel were able to work correctly with the updated code.

**Comment by orinokai** [comment]
Hi @SeanMcTernan, we're starting to take a look at this issue - but unfortunately the repro seems to be unavailable. Would it be possible to give us access again? Cheers for reporting the problem.

**Comment by orinokai** [comment]
Hi @SeanMcTernan, is it okay if we close this one or is the customer still having problems?

**Comment by SeanMcTernan** [comment]
Sorry for not replying 3 weeks ago @orinokai - Feel free to close, thank you for the follow up!
