### ISSUE TITLE
[Bug]: `NEXTAUTH_URL` environment variable is incorrect when using custom `basePath` 

### ISSUE THREAD

**Issue by Issawat** [netlify/next-runtime#1810]
### Summary

Hi Netlify team. Currently I am trying to deploy Next.js app with NextAuth and custom `basePath` setup but I found "404 page not found" on a deployed site. As I checked the API call just found that the endpoint is incorrect.

<img width="1440" alt="Screenshot 2565-11-24 at 23 14 47" src="https://user-images.githubusercontent.com/9065559/203828794-24b4bae3-959f-437f-8201-27c7ce7feace.png">

As you can see in the screenshot. The API endpoint supposed to be `https://serene-kheer-1ad0c7.netlify.app/custom-base-path/api/auth/signin/twitter` but it is actually `https://serene-kheer-1ad0c7.netlify.app/custom-base-path/signin/twitter` which is wrong. 

I thought I forgot to add `NEXTAUTH_URL` environment variable so I decided to add full endpoint to API `https://serene-kheer-1ad0c7.netlify.app/custom-base-path/api/auth/signin/twitter` since the application uses a custom `basePath`([It is documented here](https://next-auth.js.org/configuration/options#nextauth_url)). Unfortunately, the API endpoint was still wrong. It was `https://serene-kheer-1ad0c7.netlify.app/custom-base-path/api/auth/custom-base-path/signin/twitter`.

Also, I tried to identify the root cause by checking the build log. I found that `NEXTAUTH_URL` has been modified by Next.js runtime plug-in and I think this is the root cause of the issue.

My expectation is to have a correct `NEXTAUTH_URL` so it can call NextAuth API correctly.

Please be noted that the attached repository is just for simulating the issue that is happening on the project in a private repository

### Steps to reproduce

1. Go to https://serene-kheer-1ad0c7.netlify.app/custom-base-path
2. Click the link "Admin"
3. Try to login via Twitter
4. You will see the 404 page not found
5. Check the network in Chrome DevTools. You will see the API calls for NextAuth are also got 404 error

### A link to a reproduction repository

https://github.com/Issawat/nextauth-next-runtime

### Next Runtime version

 4.29.2

### More information about your build

- [ ] I am building using the CLI
- [ ] I am building using file-based configuration (`netlify.toml`)

### What OS are you using?

Mac OS

### Your netlify.toml file

<details>
  <summary>`netlify.toml`</summary>

```toml
# None
```

</details>

### Your public/_redirects file

<details>
  <summary>`_redirects`</summary>

```toml
# None
```

</details>

### Your `next.config.js` file

<details>
  <summary>`next.config.js`</summary>

```javascript
module.exports = {
  basePath: "/custom-base-path",
}
```

</details>

### Builds logs (or link to your logs)

<details>
  <summary>Build logs</summary>

https://app.netlify.com/sites/serene-kheer-1ad0c7/deploys/637f8ea048c65518d3f790b5

</details>

### Function logs

<details>
  <summary>Function logs</summary>

```
# Paste logs here
```

</details>

### .next JSON files

<details>
  <summary>generated .next JSON files</summary>

```json
{"version":1,"config":{"env":{"NEXTAUTH_URL":"https://serene-kheer-1ad0c7.netlify.app/custom-base-path"},"webpack":null,"webpackDevMiddleware":null,"eslint":{"ignoreDuringBuilds":false},"typescript":{"ignoreBuildErrors":false,"tsconfigPath":"tsconfig.json"},"distDir":".next","cleanDistDir":true,"assetPrefix":"/custom-base-path","configOrigin":"next.config.js","useFileSystemPublicRoutes":true,"generateEtags":true,"pageExtensions":["tsx","ts","jsx","js"],"target":"server","poweredByHeader":true,"compress":true,"analyticsId":"","images":{"deviceSizes":[640,750,828,1080,1200,1920,2048,3840],"imageSizes":[16,32,48,64,96,128,256,384],"path":"/custom-base-path/_next/image","loader":"default","loaderFile":"","domains":[],"disableStaticImages":false,"minimumCacheTTL":60,"formats":["image/webp"],"dangerouslyAllowSVG":false,"contentSecurityPolicy":"script-src 'none'; frame-src 'none'; sandbox;","remotePatterns":[],"unoptimized":false},"devIndicators":{"buildActivity":true,"buildActivityPosition":"bottom-right"},"onDemandEntries":{"maxInactiveAge":15000,"pagesBufferLength":2},"amp":{"canonicalBase":"/custom-base-path"},"basePath":"/custom-base-path","sassOptions":{},"trailingSlash":false,"i18n":null,"productionBrowserSourceMaps":false,"optimizeFonts":true,"excludeDefaultMomentLocales":true,"serverRuntimeConfig":{},"publicRuntimeConfig":{},"reactStrictMode":null,"httpAgentOptions":{"keepAlive":true},"outputFileTracing":true,"staticPageGenerationTimeout":60,"swcMinify":true,"experimental":{"middlewarePrefetch":"flexible","optimisticClientCache":true,"manualClientBasePath":false,"legacyBrowsers":false,"newNextLinkBehavior":true,"cpus":31,"sharedPool":true,"profiling":false,"isrFlushToDisk":true,"workerThreads":false,"pageEnv":false,"optimizeCss":false,"nextScriptWorkers":false,"scrollRestoration":false,"externalDir":false,"disableOptimizedLoading":false,"gzipSize":true,"swcFileReading":true,"craCompat":false,"esmExternals":true,"appDir":false,"isrMemoryCacheSize":52428800,"fullySpecified":false,"outputFileTracingRoot":"","swcTraceProfiling":false,"forceSwcTransforms":false,"largePageDataBytes":128000,"enableUndici":false,"adjustFontFallbacks":false,"adjustFontFallbacksWithSizeAdjust":false,"trustHostHeader":false},"configFileName":"next.config.js"},"appDir":"/opt/build/repo","files":[".next/routes-manifest.json",".next/server/pages-manifest.json",".next/build-manifest.json",".next/prerender-manifest.json",".next/server/middleware-manifest.json",".next/react-loadable-manifest.json",".next/server/font-manifest.json",".next/BUILD_ID"],"ignore":["node_modules/.pnpm/next@13.0.5_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/compiled/@ampproject/toolbox-optimizer/**/*"]}

```

</details>

**Comment by Issawat** [comment]
Actually I did a workaround (in a private repository) by creating the custom plug-in to override the Next runtime plug-in actions. Here is what I have done.

index.js
```javascript
const fs = require('fs')
const path = require('path')

const SEVER_FILENAME = 'required-server-files.json'

const BUILD_TARGETS = ['apps/dashboard/', 'apps/admin-portal/']

const checkIsInBuildTarget = publishDirectory =>
  BUILD_TARGETS.some(target => publishDirectory.includes(target))

function readJSON(jsonPath) {
  try {
    const rawdata = fs.readFileSync(jsonPath)
    return JSON.parse(rawdata)
  } catch {
    console.log('Error: Could not read config json file!')
  }
}

function getNextJSBasePath({ publish }) {
  const serverConfig = readJSON(path.join(publish, SEVER_FILENAME))
  if (serverConfig.config?.basePath) return serverConfig.config.basePath
  return ''
}

function getRequiredServerFiles(publish) {
  const configFile = path.join(publish, SEVER_FILENAME)
  return readJSON(configFile)
}

function updateRequiredServerFiles(publish, modifiedConfig) {
  const modifiedConfigData = JSON.stringify(modifiedConfig)

  fs.writeFile(path.join(publish, SEVER_FILENAME), modifiedConfigData, err => {
    if (err) throw err
    console.log('NEXTAUTH_URL is overwritten')
  })
}

function checkIsNextAuthInstalled() {
  //Surpress error and just return true or false
  try {
    require('next-auth')
    return true
  } catch {
    return false
  }
}

module.exports = {
  async onBuild({ netlifyConfig }) {
    const { publish } = netlifyConfig.build
    const isInBuildTarget = checkIsInBuildTarget(publish)
    if (isInBuildTarget) {
      const basePath = getNextJSBasePath({ publish })
      const isNextAuthInstalled = checkIsNextAuthInstalled()

      if (!isNextAuthInstalled) return

      console.log(
        'Overridding NEXTAUTH_URL env. Ignore Netlify Next.js plugin configuration'
      )

      const config = getRequiredServerFiles(publish)

      const nextAuthUrl = `${
        process.env.CONTEXT === 'production'
          ? process.env.URL
          : process.env.DEPLOY_PRIME_URL
      }${basePath}/api/auth`

      config.config.env.NEXTAUTH_URL = nextAuthUrl

      updateRequiredServerFiles(publish, config)

      console.log('Overriden NEXTAUTH_URL:', nextAuthUrl)
    } else {
      console.log('This is not a project with NextAuth, skipped!')
    }
  },
}
```

maniifest.yml
```yml
name: netlify-plugin-brikl-nextauth
```

netlify.toml
```toml
...
[[plugins]]
  package = "/netlify/plugins/netlify-plugin-brikl-nextauth"
...
```

This implementation works smoothly but that is just for single project. I think it is better to fix from Netlify's plug-in. That would be a benefit for everyone.

**Comment by sarahetter** [comment]
Closing as stale
