### ISSUE TITLE
Investigate correct behaviour for middleware rewrites to SSG page with query string

### ISSUE THREAD

**Issue by ascorbic** [netlify/next-runtime#1821]
The e2e tests have a test which [uses middleware](https://github.com/netlify/next-runtime/blob/main/test/e2e/modified-tests/middleware-general/app/middleware.js#L63-L67) to add a query param to a rewrite. However [the test checks](https://github.com/netlify/next-runtime/blob/main/test/e2e/modified-tests/middleware-general/test/index.test.ts#L189) that that param is *not* added. Because of this, the test is currently disabled. We should check what the actual expected behavbiour is here

**Comment by serhalp** [comment]
Superseded by v5.
