### ISSUE TITLE
Middleware running at CDN vs origin

### ISSUE THREAD

**Issue by BrandonALittle** [netlify/next-runtime#1826]
NextJS version: 13.0.3
@netlify/plugin-nextjs: 4.29.1

We recently upgraded to the latest version of the plugin (at the time, that was 4.29.1), as instructed by the deployment log on Netlify. This resulted in a change to how the middleware is run (CDN vs origin). 

We run a cloudfront distribution that distributes traffic from our public URL to our netlify URL.

We use the next middleware to add a cookie and then redirect requests to a particular route in our application `/beta` back to the origin, which is our public URL.

Since upgrading to the latest version of the plugin, this functionality is broken because the host and origin on the request coming into the middleware is no longer the public URL, but rather the netlify URL. So users hit `/beta` and are redirected to a Netlify URL.

Is there a way to fix this?

**Comment by ericapisani** [comment]
If you'd like to opt-out of the middleware running at the edge just to get things working again, you can do so by setting the [`NEXT_DISABLE_NETLIFY_EDGE`](https://docs.netlify.com/integrations/frameworks/next-js/middleware/#opt-out-of-netlify-edge-functions) environment variable.

But assuming you'd like to try and use middleware at the edge and maintain the existing logic of the site, we'd need to see an example of the code that you're using to achieve what you've outlined above to make sure we're not misunderstanding the implementation of what you have in your codebase before making any suggestions (could be a contrived example). 

Also - based on your description above, can I confirm you're using host-based or origin-based routing for the distribution of traffic?

**Comment by ascorbic** [comment]
Hi. I'm closing this because we've not heard back for two weeks. Please open a new issue with the extra details if you still have the problem.
