### ISSUE TITLE
[Bug]: Next 13 appdir issue, SPA becomes MPA navigation

### ISSUE THREAD

**Issue by antonybudianto** [netlify/next-runtime#1828]
### Summary

I used appdir release of next-runtime, and Next 13 appdir, and after deploy, I realized that the usual SPA navigation doesn't work anymore, when we click a link, it always does a full refresh. This doesn't happen on local (npm run build+start) and Vercel.

Maybe this is related? https://github.com/vercel/next.js/issues/41885

### Steps to reproduce

1. Clone https://github.com/antonybudianto/next-antonybudianto, `main` branch
2. npm run build
3. npm run start, try click Blog, it still does SPA navigation correctly
4. Try to deploy to netlify, it doesn't do SPA navigation anymore, https://antonybudianto.com/

### A link to a reproduction repository

https://github.com/antonybudianto/next-antonybudianto or
https://github.com/antonybudianto/next-antonybudianto/pull/18 to see Netlify and Vercel deploy link

### Next Runtime version

4.29.3-appdir.0

### More information about your build

- [ ] I am building using the CLI
- [X] I am building using file-based configuration (`netlify.toml`)

### What OS are you using?

Mac OS

### Your netlify.toml file

<details>
  <summary>`netlify.toml`</summary>

```toml
[[plugins]]
package = "@netlify/plugin-nextjs"
```

</details>

### Your public/_redirects file

<details>
  <summary>`_redirects`</summary>

```toml
# Paste content of your `_redirects` file here
```

</details>

### Your `next.config.js` file

<details>
  <summary>`next.config.js`</summary>

```toml
/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: false,
  swcMinify: true,
  experimental: {
    appDir: true,
  },
};

module.exports = nextConfig;

```

</details>

### Builds logs (or link to your logs)

<details>
  <summary>Build logs</summary>

```
# Paste logs here
```

</details>

### Function logs

<details>
  <summary>Function logs</summary>

```
# Paste logs here
```

</details>

### .next JSON files

<details>
  <summary>generated .next JSON files</summary>

```
# Paste file contents here. Please check there isn't any private info in them
# You can either build locally, or download the deploy from Netlify by clicking the arrow next to the deploy time.
```

</details>

**Comment by antonybudianto** [comment]
resolve in :
    "@netlify/plugin-nextjs": "4.29.3" 🙏🏻

**Comment by khuezy** [comment]
@antonybudianto do you know what changed to fix this?
