### ISSUE TITLE
[Bug]: .next directory returns a 404 error page 

### ISSUE THREAD

**Issue by kaf-lamed-beyt** [netlify/next-runtime#1836]
### Summary

When I set my publish dir on netlify to .next, because I'm using `next build` as my command, so I can get the API routes feature. I get a 404 page not found error. Could this be an issue exclusive to netlify alone?

I remember this being possible in the older versions of Next.js, API routes support was out-of-the-box.

I read up on an answer you suggested in a GitHub discussion stating how `next build` solves the problem. Well,  I think it does to some extent at least. But, the issue here is that platforms like Netlify needs a/an index.html file to serve when I set my publish dir to `.next` instead of `out` when I'm using `next build` right?

And the content in the `.next` folder includes a subdir like `server`, `static` and others I can't remember anymore. 

Is there a way I can tap into the superpower of Next.js API routes when I'm using `next build`. "Yes, definitely" is the reply I'd get, perhaps, and still be able to allow Netlify bots to find an index.html file that can be served? because last time I checked, I didn't find any.

My site ([http://meje.dev](https://t.co/hVYtSWcxKc)) taps into the SSR feature that Next provides, and currently, I'm adding a little bit of backend stuff to it -- a few server-side calls here and there.

I definitely need the API route. How do I get this to work when I'm using `next build` on [@netlify](https://twitter.com/Netlify)
. Or is this only possible on 
[@vercel](https://twitter.com/vercel)
?

PS: this was extracted from a thread I made as a reply to [Lee Robinson's reply to my tweet.](https://twitter.com/leeerob/status/1601605241203412992)

### Steps to reproduce

[my repo](https://github.com/kaf-lamed-beyt/seven)

### A link to a reproduction repository

https://github.com/kaf-lamed-beyt/seven

### Next Runtime version

v4.29.3

### More information about your build

- [ ] I am building using the CLI
- [ ] I am building using file-based configuration (`netlify.toml`)

### What OS are you using?

Linux

### Your netlify.toml file

<details>
  <summary>`netlify.toml`</summary>

```toml
# Paste content of your `netlify.toml` file here
```

</details>

### Your public/_redirects file

<details>
  <summary>`_redirects`</summary>

```toml
# Paste content of your `_redirects` file here
```

</details>

### Your `next.config.js` file

<details>
  <summary>`next.config.js`</summary>

```toml
# Paste content of your `next.config.js` file here. Check there is no private info in there.
```

</details>

### Builds logs (or link to your logs)

<details>
  <summary>Build logs</summary>

```
# Paste logs here
```

</details>

### Function logs

<details>
  <summary>Function logs</summary>

```
# Paste logs here
```

</details>

### .next JSON files

<details>
  <summary>generated .next JSON files</summary>

```
# Paste file contents here. Please check there isn't any private info in them
# You can either build locally, or download the deploy from Netlify by clicking the arrow next to the deploy time.
```

</details>

**Comment by kaf-lamed-beyt** [comment]
Oh Dang!

Forgot it is private. I'll share the link to the build logs now.

**Comment by kaf-lamed-beyt** [comment]
[Here you go](https://app.netlify.com/sites/meje/deploys/6396fc6c616b1f00088d3902)

**Comment by ascorbic** [comment]
It's showing that the Next Runtime has been disabled. Have you set `NETLIFY_NEXT_PLUGIN_SKIP` to true?

**Comment by kaf-lamed-beyt** [comment]
I don't think I have.

Do you mind telling me where I can find it?

**Comment by kaf-lamed-beyt** [comment]
Found it.

Realized that it is an environment variable, and I've changed the value to false

**Comment by kaf-lamed-beyt** [comment]
**"Site is Live ✨"** 

Thank you for your help @ascorbic!

**Comment by ascorbic** [comment]
Great! The runtime needs to be disabled when you're using `next export`, but is needed for all other cases.

**Comment by nickytonline** [comment]
Looks like this is resolved @kaf-lamed-beyt, so I'm going to go ahead and close this.

**Comment by kaf-lamed-beyt** [comment]
Yes, it is.

Thanks
