### ISSUE TITLE
[Bug]: appDir pages not varying cache on RSC header

### ISSUE THREAD

**Issue by NADESHIKON** [netlify/next-runtime#1844]
### Summary

I tried fetching in Postman and *sometimes* Netlify will make user download a file with following content: https://pastebin.com/raw/QMZ7wVuB

which I assume is Next.js's server component props

### Steps to reproduce

View the site

### A link to a reproduction repository

https://github.com/Enime-Project/enime.moe/tree/next

### Next Runtime version

4.29.3-appdir.0

### More information about your build

- [ ] I am building using the CLI
- [ ] I am building using file-based configuration (`netlify.toml`)

### What OS are you using?

None

### Your netlify.toml file

<details>
  <summary>`netlify.toml`</summary>

```toml
# Paste content of your `netlify.toml` file here
```

</details>

### Your public/_redirects file

<details>
  <summary>`_redirects`</summary>

```toml
# Paste content of your `_redirects` file here
```

</details>

### Your `next.config.js` file

<details>
  <summary>`next.config.js`</summary>

```toml
# Paste content of your `next.config.js` file here. Check there is no private info in there.
```

</details>

### Builds logs (or link to your logs)

<details>
  <summary>Build logs</summary>

```
# Paste logs here
```

</details>

### Function logs

<details>
  <summary>Function logs</summary>

```
# Paste logs here
```

</details>

### .next JSON files

<details>
  <summary>generated .next JSON files</summary>

```
# Paste file contents here. Please check there isn't any private info in them
# You can either build locally, or download the deploy from Netlify by clicking the arrow next to the deploy time.
```

</details>

**Comment by ascorbic** [comment]
Does this happen with a browser or just Postman? That content is the React Server Components streaming updates

**Comment by ascorbic** [comment]
Could you try updating the runtime to `4.29.4`. This is a new version which supports appDir in the normal release, though it isn't auto-installed yet.

**Comment by NADESHIKON** [comment]
> Could you try updating the runtime to `4.29.4`. This is a new version which supports appDir in the normal release, though it isn't auto-installed yet.

Updated to 4.29.4, the issue still exists.

**Comment by ascorbic** [comment]
I think I have a diagnosis for this. I'm going to rename this and merge with an issue that's kind've the opposite, but a manifestation of the same problem.
