### ISSUE TITLE
[Bug]: appdir Next 13 SPA works, but when visit directly, it downloads a file instead

### ISSUE THREAD

**Issue by antonybudianto** [netlify/next-runtime#1847]
### Summary

Nextjs 13 with appdir, deployed with Netlify have issue where if the page is visited directly, it downloads a file instead...
This doesn't happen with local build+start

Sample: https://antonybudianto.com/blog/hello

### Steps to reproduce

1. Clone https://github.com/antonybudianto/next-antonybudianto/
2. Deploy with Netlify
3. Try visit page /blog/hello directly (not via links)
4. It will download a file on browser instead of opening the page

### A link to a reproduction repository

https://github.com/antonybudianto/next-antonybudianto/

### Next Runtime version

4.29.3

### More information about your build

- [ ] I am building using the CLI
- [X] I am building using file-based configuration (`netlify.toml`)

### What OS are you using?

Mac OS

### Your netlify.toml file

<details>
  <summary>`netlify.toml`</summary>

```toml
[[plugins]]
package = "@netlify/plugin-nextjs"
```

</details>

### Your public/_redirects file

<details>
  <summary>`_redirects`</summary>

```toml
# Paste content of your `_redirects` file here
```

</details>

### Your `next.config.js` file

<details>
  <summary>`next.config.js`</summary>

```ts
/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: false,
  swcMinify: true,
  experimental: {
    appDir: true,
  },
};

module.exports = nextConfig;

```

</details>

### Builds logs (or link to your logs)

<details>
  <summary>Build logs</summary>

```
# Paste logs here
```

</details>

### Function logs

<details>
  <summary>Function logs</summary>

```
# Paste logs here
```

</details>

### .next JSON files

<details>
  <summary>generated .next JSON files</summary>

```
# Paste file contents here. Please check there isn't any private info in them
# You can either build locally, or download the deploy from Netlify by clicking the arrow next to the deploy time.
```

</details>

**Comment by ascorbic** [comment]
Hi. Next appDir isn't supported in the default version of the runtime yet. Can you try again after installing `@netlify/plugin-nextjs@latest` in your project?

**Comment by antonybudianto** [comment]
Let me try with latest tag..

**Comment by antonybudianto** [comment]
Ah it's good now, however, the SPA navigation breaks now 😅

**Comment by ascorbic** [comment]
Do you have a live example?

**Comment by ascorbic** [comment]
OK, I think I've diagnosed this, so I'm closing this in favour #1844 which is the same issue.
