### ISSUE TITLE
[Bug]: `ntl dev` with ssl certificates does not work with the next plugin

### ISSUE THREAD

**Issue by lukasholzer** [netlify/next-runtime#1877]
### Summary

The new version of the next plugin does not work with https configuration anymore. Old version `@netlify/plugin-nextjs@4.8.0` still works.

developing with ssl is sometimes needed when working with headless CMS for example https://www.storyblok.com/ (as you run the site inside their iframe which requires https)

![CleanShot 2023-01-11 at 10 29 19](https://user-images.githubusercontent.com/11156362/211769111-2434aba5-e6e5-4f6c-8653-90547f75c16d.png)

Crashing with this error:
```
Error: There was an internal error while processing your request
    at https://639708f6d7f813000870695c--edge.netlify.app/bootstrap/function_chain.ts:130:15
    at async backoffRetry (https://639708f6d7f813000870695c--edge.netlify.app/bootstrap/retry.ts:24:14)
    at async FunctionChain.fetchOrigin (https://639708f6d7f813000870695c--edge.netlify.app/bootstrap/function_chain.ts:111:17)
    at async FunctionChain.run (https://639708f6d7f813000870695c--edge.netlify.app/bootstrap/function_chain.ts:288:22)
    at async handleRequest (https://639708f6d7f813000870695c--edge.netlify.app/bootstrap/handler.ts:59:22)
    at async Server.#respond (https://deno.land/std@0.136.0/http/server.ts:298:18)
```

### Steps to reproduce

1. Create a next.js site
2. generate with [mkcert](https://github.com/FiloSottile/mkcert) a new pair of local certificates
3. Adapt the `netlify.toml` with:
    ```toml
    [dev.https]
    certFile = "localhost.pem"
    keyFile = "localhost-key.pem"
    ```
4. Run `ntl dev`

### A link to a reproduction repository

https://github.com/lukasholzer/netlify-next-redirect-issue/tree/https-issue

### Next Runtime version

4.29.4

### More information about your build

- [X] I am building using the CLI
- [X] I am building using file-based configuration (`netlify.toml`)

### What OS are you using?

Mac OS

### Your netlify.toml file

<details>
  <summary>`netlify.toml`</summary>

```toml
# Paste content of your `netlify.toml` file here
```

</details>

### Your public/_redirects file

<details>
  <summary>`_redirects`</summary>

```toml
[dev.https]
certFile = "localhost.pem"
keyFile = "localhost-key.pem"

```

</details>

### Your `next.config.js` file

<details>
  <summary>`next.config.js`</summary>

```toml
/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
}

module.exports = nextConfig
```

</details>

### Builds logs (or link to your logs)

<details>
  <summary>Build logs</summary>

```
# Paste logs here
```

</details>

### Function logs

<details>
  <summary>Function logs</summary>

```
# Paste logs here
```

</details>

### .next JSON files

<details>
  <summary>generated .next JSON files</summary>

```
# Paste file contents here. Please check there isn't any private info in them
# You can either build locally, or download the deploy from Netlify by clicking the arrow next to the deploy time.
```

</details>

**Comment by sarahetter** [comment]
Investigation notes:
Most recent functioning version: `4.17.1-runtime.0`.

**Comment by sarahetter** [comment]
This is fixed by updating the cli 😆 
`netlify-cli/12.9.2` works when running `ntl dev` on a next site with ssl
