### ISSUE TITLE
[Bug]: edge rendered dynamic routes do not correctly parse slugs into params

### ISSUE THREAD

**Issue by orinokai** [netlify/next-runtime#1890]
### Summary

Dynamic routes rendered on the edge with `runtime: 'experimental-edge'` do not correctly parse the slug into the page parameters.

This is demonstrated by the failing e2e test: `edge-render-getserversideprops`

### Steps to reproduce

1. Clone the repro and deploy to Netlify
2. Visit `/123?hello=world`

Expected: `{"url":"/123?hello=world","query": {"hello":"world" ,"id":"123"},"params": {"id":"123"},"now": 1673955487763}`

Actual: `{"url":"/123?hello=world","query": {"hello":"world"},"now": 1673955487763}`

### A link to a reproduction repository

https://github.com/orinokai/test-next-edge-slug

### Next Runtime version

4.30.0

### More information about your build

- [ ] I am building using the CLI
- [ ] I am building using file-based configuration (`netlify.toml`)

### What OS are you using?

None

**Comment by taty2010** [comment]
Marc and I were looking into this issue and are needing more info on what's going on. @ascorbic are you already working on this?

**Comment by ascorbic** [comment]
I started looking at it, and it's a tricky one. It might require edge router
