### ISSUE TITLE
Role based redirects using _redirects

### ISSUE THREAD

**Issue by melono6** [netlify/next-runtime#1901]
Today i encountered an issue with trying to use role based redirect in the _redirects file

eg:
/about 200! Role=authorized
/about /.netlify/functions/login 401!

But then i found these rules only worked for pages that were statically built at buildtime (so they had a .html file)
I realised this was because i was overriding the standard nextjs redirects that would take the user to the appropriate function and build the page on demand or show a 404 error.

I was able to resolve my issue withe the following config:
/about /.netlify/functions/___netlify-handler 200! Role=authorized
/about /.netlify/functions/login 401!

Question:
Does this seem like the correct solution, should i expect any issues with the above config?

**Comment by ascorbic** [comment]
Hi. It's not ideal, but yes I think that's the only realistic approach. You'll need to do something with the data route too if people are likely to navigate there. You can set a static build id by adding this to your next.config.js:

```js
generateBuildId: () => "build-id",
```

...and then add this route to your rules:

`/_next/data/build-id/about.json`
