### ISSUE TITLE
[Bug]: Build warning points to 404 at https://ntl.fyi/next-rewrites

### ISSUE THREAD

**Issue by ThangHuuVu** [netlify/next-runtime#1930]
### Summary

When configuring in the _redirects file, I got the following warning:
```
11:17:04 PM: You have the following Netlify rewrites that might cause conflicts with the Next.js Runtime:
11:17:04 PM: 
11:17:04 PM: - /authjs/?code=:code&state=:state /authjs/ 200
11:17:04 PM: - /authjs/?state=:state&code=:code /authjs/ 200
11:17:04 PM: 
11:17:04 PM: For more information, see https://ntl.fyi/next-rewrites
```
When I go to https://ntl.fyi/next-rewrites, it points to a 404 page: https://github.com/netlify/next-runtime/blob/main/docs/redirects-rewrites.md

### Steps to reproduce

1. Deploy a next.js app on Netlify. Configure a rewrite rule that prompts the warning
2. Observe the deployment output

### A link to a reproduction repository

https://github.com/nextauthjs/auth-with-proxy

### Next Runtime version

v4.30.4

### More information about your build

- [ ] I am building using the CLI
- [ ] I am building using file-based configuration (`netlify.toml`)

### What OS are you using?

None

### Your netlify.toml file

<details>
  <summary>`netlify.toml`</summary>

```toml
# Paste content of your `netlify.toml` file here
```

</details>

### Your public/_redirects file

<details>
  <summary>`_redirects`</summary>

```
# Paste content of your `_redirects` file here
/authjs/?code=:code&state=:state /authjs/ 200!
/authjs/?state=:state&code=:code /authjs/ 200!
/authjs/* https://next-auth-behind-cdn.vercel.app/authjs/:splat 200!
```

</details>

### Your `next.config.js` file

<details>
  <summary>`next.config.js`</summary>

```js
# Paste content of your `next.config.js` file here. Check there is no private info in there.
/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
}

module.exports = nextConfig
```

</details>

### Builds logs (or link to your logs)

<details>
  <summary>Build logs</summary>

```
# https://app.netlify.com/sites/authjs-with-proxy/deploys/63f0f9d23bec4d0008249a3a
11:17:04 PM: Next.js cache saved.
11:17:04 PM: You have the following Netlify rewrites that might cause conflicts with the Next.js Runtime:
11:17:04 PM: 
11:17:04 PM: - /authjs/?code=:code&state=:state /authjs/ 200
11:17:04 PM: - /authjs/?state=:state&code=:code /authjs/ 200
11:17:04 PM: 
11:17:04 PM: For more information, see https://ntl.fyi/next-rewrites
11:17:04 PM: ​
11:17:04 PM: (@netlify/plugin-nextjs onPostBuild completed in 66ms)
```

</details>

### Function logs

<details>
  <summary>Function logs</summary>

```
# Paste logs here
```

</details>

### .next JSON files

<details>
  <summary>generated .next JSON files</summary>

```
# Paste file contents here. Please check there isn't any private info in them
# You can either build locally, or download the deploy from Netlify by clicking the arrow next to the deploy time.
```

</details>

**Comment by nickytonline** [comment]
@stephmarie17, would you happen to have access to make the change? I believe it needs to point to https://docs.netlify.com/integrations/frameworks/next-js/redirects-and-rewrites ?

**Comment by MarcL** [comment]
Thanks for raising this issue, @ThangHuuVu.

This has occurred because we've removed the documentation from the Next.js runtime repository so our Netlify documentation is our source of truth. I've now updated the shortlink so it points to the correct page.

**Comment by ThangHuuVu** [comment]
Thanks for the quick fix @MarcL 🫶 If you have some time, could you help me answer [this discussion](https://github.com/netlify/next-runtime/discussions/1931) as well? 😛 It's how I got to know about this issue. Thank you in advance
