### ISSUE TITLE
Bug: `appDir` applications can have `dataRoute: null`

### ISSUE THREAD

**Issue by Skn0tt** [netlify/next-runtime#1940]
When you run `next build` on https://github.com/redmonkez12/interactive-rating-component/tree/079f65a9b1d84efe2c1032dc01c022b46a7c0fb5, then `prerender-manifest.json` will contain

```json
"/api/hello": {
    "initialHeaders": { "content-type": "text/plain;charset=UTF-8" },
    "initialRevalidateSeconds": false,
    "srcRoute": "/api/hello",
    "dataRoute": null
  }
```

Our runtime currently can't handle that, and will throw an error here, because `dataRoute is null`:

https://github.com/netlify/next-runtime/blob/72ab895be865402fa0d92431f293129c70ae6c8b/packages/runtime/src/templates/edge-shared/rsc-data.ts#L38

To fix that, we should update the Next.js version that this repo is pulling TS types from, and fix all places where the types now fail.

**Comment by MarcL** [comment]
Feels like this is a high priority so I've added it to the current iteration as an "up next".

**Comment by voyagebagage** [comment]
> When you run `next build` on https://github.com/redmonkez12/interactive-rating-component/tree/079f65a9b1d84efe2c1032dc01c022b46a7c0fb5, then `prerender-manifest.json` will contain
> 
> ```json
> "/api/hello": {
>     "initialHeaders": { "content-type": "text/plain;charset=UTF-8" },
>     "initialRevalidateSeconds": false,
>     "srcRoute": "/api/hello",
>     "dataRoute": null
>   }
> ```
> 
> Our runtime currently can't handle that, and will throw an error here, because `dataRoute is null`:
> 
> https://github.com/netlify/next-runtime/blob/72ab895be865402fa0d92431f293129c70ae6c8b/packages/runtime/src/templates/edge-shared/rsc-data.ts#L38
> 
> To fix that, we should update the Next.js version that this repo is pulling TS types from, and fix all places where the types now fail.

so no fix yet right? 
I have same problem I have tried to deploy my project at the start without almost any code, just setting tailwind and chakra ui on Next13 last version but the deploy is failing the same way

[`REPO`](https://github.com/voyagebagage/portfolio)

**Comment by Hrishikesh-K** [comment]
Some threads where users are seeing this as an issue:

https://netlify.zendesk.com/agent/tickets/137136
https://netlify.zendesk.com/agent/tickets/137386
https://answers.netlify.com/t/87475
https://answers.netlify.com/t/88394
https://answers.netlify.com/t/86328

**Comment by narbota** [comment]
Hello, I'm getting the same error as well when deploying Nextjs 13 site https://app.netlify.com/sites/next-13-trail/deploys/6423617b0dc578000711a6fe   
Internal error during Edge functions budling" 5:53:04 PM:   5. Edge Functions bundling                                   
5:53:04 PM: ────────────────────────────────────────────────────────────────
5:53:04 PM:
5:53:04 PM: Packaging Edge Functions from .netlify/edge-functions directory:
5:53:04 PM:  - rsc-data
5:53:05 PM: TypeError: Cannot read properties of null (reading 'endsWith')
5:53:05 PM:     at file:///opt/build/repo/.netlify/edge-functions/edge-shared/rsc-data.ts:38:48
5:53:05 PM:     at Array.filter (<anonymous>)
5:53:05 PM:     at getRscDataRouter (file:///opt/build/repo/.netlify/edge-functions/edge-shared/rsc-data.ts:38:8)
5:53:05 PM:     at file:///opt/build/repo/.netlify/edge-functions/rsc-data/rsc-data.ts:4:17
5:53:05 PM: Could not load edge function at '/opt/build/repo/.netlify/edge-functions/rsc-data/rsc-data.ts'
5:53:05 PM:
5:53:05 PM:   Internal error during "Edge Functions bundling"              
5:53:05 PM: ────────────────────────────────────────────────────────────────
5:53:05 PM:
5:53:05 PM:   Error message
5:53:05 PM:   TypeError: Expected a string

**Comment by nickytonline** [comment]
As mentioned in Slack @narbota, we're currently rolling out v. 4.33.0. If they're not auto-installing, they can upgrade to the latest version of the runtime.

**Comment by nickytonline** [comment]
@Fox32, apologies, but I mispoke. This fix didn't roll out in v. 4.33.0. I'm adding it to the next release.

**Comment by proyectosynergosorg** [comment]
Hi there, I've been trying unsuccessfully to deploy Next (v13.2.4) with experimental appDir: true BUT with no edge functions at all. It's way impossible having this up and running, nevertheless my setup works fine locally. Also, a different Github project/repo using a previous version of next (13.1.6) worked like a charm when deployed in Netlify, but with the latest one, after trying and trying different workarounds suggested by community users, I keep getting this:

![capture-netlify-deploy-fail|690x334](upload://aNyKTbSCSjet4O2N9fwggAywGCD.png)

I got nothing fancy, just a fresh nextjs using --typescript... and appDir=true. My  dependencies (package.json):

"dependencies": {
    "@netlify/plugin-nextjs": "^4.33.0",
    "@types/node": "18.15.11",
    "@types/react": "18.0.33",
    "@types/react-dom": "18.0.11",
    "next": "13.2.4",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "typescript": "5.0.3"
  },
  "devDependencies": {
    "@typescript-eslint/eslint-plugin": "^5.57.1",
    "@typescript-eslint/parser": "^5.57.1",
    "eslint": "^8.37.0"
  }

My next.config.js:

/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  experimental: {
    appDir: true,
  },
}
module.exports = nextConfig

...it's really frustrating not seeing any advance on this. Thanks in advance

**Comment by nickytonline** [comment]
@proyectosynergosorg, the fix in #2018 will sort this out. I'm looking to get it merged tomorrow.

**Comment by Reniactor** [comment]
Ohhh so it **is** a bug on NextJs. Hopefully i'll get to try the fix out tomorrow ;-; 

Also, is there any easy way to a workaround or something? :>

**Comment by kindrift-vt** [comment]
@nickytonline Any movement on the fix? I see #2018 was merged but I'm still running into the same issue on my deploys that have internal errors on edge function bundling. I posted on a thread here: https://answers.netlify.com/t/next-app-edge-function-bundling-error/89530

**Comment by Reniactor** [comment]
@kindrift-vt i honestly just used vercel page to deploy the app and it's working perfectly. Didn't have this issue there

**Comment by nickytonline** [comment]
This is fixed and will start rolling out next week @kindrift-vt.

**Comment by vst** [comment]
For the record: with Next.js v13.2, removing `/api` directory allowed us to deploy the app Netlify. With Next.js v13.3, this approach no longer works.

**Comment by myko1328** [comment]
hey @nickytonline . I've installed the latest update `("@netlify/plugin-nextjs": "^4.34.0")`  but encountered another error.


<img width="517" alt="Screenshot_107" src="https://user-images.githubusercontent.com/5935167/231190573-44771141-5639-490e-8e47-f308bde66d60.png">

**Comment by nickytonline** [comment]
> hey @nickytonline . I've installed the latest update `("@netlify/plugin-nextjs": "^4.34.0")` but encountered another error.
> 
> <img alt="Screenshot_107" width="517" src="https://user-images.githubusercontent.com/5935167/231190573-44771141-5639-490e-8e47-f308bde66d60.png">

@myko1328, this error seems unrelated to the original issue. Mind creating a separate issue for this?

**Comment by kindrift-vt** [comment]
> > hey @nickytonline . I've installed the latest update `("@netlify/plugin-nextjs": "^4.34.0")` but encountered another error.
> 
> @myko1328, this error seems unrelated to the original issue. Mind creating a separate issue for this?

Can confirm that @myko1328's error now occurs. this might be related in the sense that the error only surfaced after the fix. Should I make a new issue linking to this?

**Comment by kindrift-vt** [comment]
> For the record: with Next.js v13.2, removing `/api` directory allowed us to deploy the app Netlify. With Next.js v13.3, this approach no longer works.

Did you remove the api directory altogether or remove them from either the `/app` or `/pages` dir?

**Comment by vst** [comment]
> > For the record: with Next.js v13.2, removing `/api` directory allowed us to deploy the app Netlify. With Next.js v13.3, this approach no longer works.
> 
> Did you remove the api directory altogether or remove them from either the `/app` or `/pages` dir?

I removed the api directory altogether. This is how I managed to build before v13.3.

**Comment by Maxservais** [comment]
Also facing the same issue 
![image](https://user-images.githubusercontent.com/43566493/231528902-75f370ec-f038-4222-9106-bb6a0608ae7d.png)

**Comment by jonverne1** [comment]
Same error message as above using the latest versions of Next and the plugin. My Project is created via create-next-app with the appDir. Otherwise I haven't made any other major changes. Runs fine locally.

**Comment by miketalley** [comment]
Hello, I am experiencing this issue as well. I'm also using `appDir` on a project creates with `create-next-app`.

```
  5. Edge Functions bundling                                    
────────────────────────────────────────────────────────────────

Packaging Edge Functions from .netlify/edge-functions directory:
 - rsc-data

Packaging Edge Functions from netlify/edge-functions directory:
 - hello
Local version of types is up-to-date: 643581608391e3000851cc94
No globalVersion or semver not satisfied. globalVersion: undefined, versionRange: ^1.22.0
Using cached Deno CLI from /Users/miketalley/Library/Preferences/netlify/deno-cli/deno
No globalVersion or semver not satisfied. globalVersion: undefined, versionRange: ^1.22.0
No globalVersion or semver not satisfied. globalVersion: undefined, versionRange: ^1.22.0
Using cached Deno CLI from /Users/miketalley/Library/Preferences/netlify/deno-cli/deno
Using cached Deno CLI from /Users/miketalley/Library/Preferences/netlify/deno-cli/deno
No in-source config found for edge function at '/Users/miketalley/Repos/liblab-lotr/netlify/edge-functions/hello.ts'
TypeError: Cannot read properties of null (reading 'endsWith')
    at file:///Users/miketalley/Repos/liblab-lotr/.netlify/edge-functions/edge-shared/rsc-data.ts:38:48
    at Array.filter (<anonymous>)
    at getRscDataRouter (file:///Users/miketalley/Repos/liblab-lotr/.netlify/edge-functions/edge-shared/rsc-data.ts:38:8)
    at file:///Users/miketalley/Repos/liblab-lotr/.netlify/edge-functions/rsc-data/rsc-data.ts:4:17
Could not load edge function at '/Users/miketalley/Repos/liblab-lotr/.netlify/edge-functions/rsc-data/rsc-data.ts'

  Internal error during "Edge Functions bundling"               
────────────────────────────────────────────────────────────────

  Error message
  TypeError: Expected a string

  Error location
  During Edge Functions bundling
      at module.exports (/usr/local/lib/node_modules/netlify-cli/node_modules/@netlify/edge-bundler/node_modules/glob-to-regexp/index.js:3:11)
      at pathToRegularExpression (file:///usr/local/lib/node_modules/netlify-cli/node_modules/@netlify/edge-bundler/dist/node/manifest.js:94:31)
      at getRegularExpression (file:///usr/local/lib/node_modules/netlify-cli/node_modules/@netlify/edge-bundler/dist/node/manifest.js:115:12)
      at file:///usr/local/lib/node_modules/netlify-cli/node_modules/@netlify/edge-bundler/dist/node/manifest.js:60:25
      at Array.forEach (<anonymous>)
      at generateManifest (file:///usr/local/lib/node_modules/netlify-cli/node_modules/@netlify/edge-bundler/dist/node/manifest.js:55:18)
      at writeManifest (file:///usr/local/lib/node_modules/netlify-cli/node_modules/@netlify/edge-bundler/dist/node/manifest.js:136:22)
      at bundle (file:///usr/local/lib/node_modules/netlify-cli/node_modules/@netlify/edge-bundler/dist/node/bundler.js:78:28)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async coreStep (file:///usr/local/lib/node_modules/netlify-cli/node_modules/@netlify/build/lib/plugins_core/edge_functions/index.js:35:30)
```

**Comment by nickytonline** [comment]
@miketalley an others, the fix for this is in the latest version of the Next.js runtime, [4.34.0](https://github.com/netlify/next-runtime/releases/tag/plugin-nextjs-v4.34.0). Is that the version of the Next.js runtime you see in your logs @miketalley?

**Comment by miketalley** [comment]
Yes

```
2:12:10 PM: ❯ Using Next.js Runtime - v4.34.0
```
