### ISSUE TITLE
Support Custom Route Handlers

### ISSUE THREAD

**Issue by nickytonline** [netlify/next-runtime#1941]
Next.js 13.2 introduces custom route handlers. See https://nextjs.org/blog/next-13-2#custom-route-handlers. We currently handle routes in pages/api, but we'll need to support this as well for Next 13 users.

For the most part, this should work out of the box because it will be reflected in the routes manifest, but we may need to tweak our logic a bit to support this.

**Comment by orinokai** [comment]
This is now tested and can confirm it works out of the box 🎉
