### ISSUE TITLE
modified-tests/edge-render-getserversideprops "should respond to _next/data for index correctly" test is flaky

### ISSUE THREAD

**Issue by sarahetter** [netlify/next-runtime#1953]
https://github.com/netlify/next-runtime/actions/runs/4305174453/jobs/7507961606

This test seems to mostly fail, but sometimes pass in CI. It always passes locally, sending `null` instead of `undefined` as the value.

**Comment by ascorbic** [comment]
This is a genuine failure. It returns the wrong thing because one it's matching the wrong page. I think there's a ticket, but it's where a dynamic route is matching instead of the static one.

**Comment by sarahetter** [comment]
@ascorbic is this a regression? I can't find a ticket related to this, and I'm not sure why it's not skipped.

**Comment by ascorbic** [comment]
I think Rob was looking at it

**Comment by sarahetter** [comment]
Added to another issue, closing
