### ISSUE TITLE
Plugin should warn if steps are skipped because of `NETLIFY_NEXT_PLUGIN_SKIP`

### ISSUE THREAD

**Issue by essenmitsosse** [netlify/next-runtime#1994]
I just debugged for half a day to find out why I couldn't deploy to Netlify; even though I was following all of the tutorials and example projects, everything worked fine locally, and I tried a thousand things. Ultimately, I realized that my project still had `NETLIFY_NEXT_PLUGIN_SKIP` set to `true` in the Netlify GUI. This is also a shortcoming of Netlify. 

But it would be great if the plugin could output at least one line telling the user that the plugin will skip steps. What is even more confusing is that the `onBuild` actually gets logged, and the only thing that made me suspicious was that it took only 3ms.

```
11:27:36 PM:   3. @netlify/plugin-nextjs (onBuild event)                     
11:27:37 PM: Post processing - HTML
11:27:36 PM: ────────────────────────────────────────────────────────────────
11:27:36 PM: ​
11:27:36 PM: ​
11:27:36 PM: (@netlify/plugin-nextjs onBuild completed in 3ms)
```

A simple _"Skipping `onBuild` because of `NETLIFY_NEXT_PLUGIN_SKIP`"_ would be super helpful for other unfortunate souls in the future and won't hurt anyone else.

**Comment by MarcL** [comment]
Hi @essenmitsosse. Thanks for raising this issue.

Can I confirm if you got a post-build message in your deploy logs?
Looking at the code, we should be warning you that `NETLIFY_NEXT_PLUGIN_SKIP` was set here:

https://github.com/netlify/next-runtime/blob/main/packages/runtime/src/index.ts#L206-L216

You should see a warning in the post-build step:

> Next cache was stored, but all other functions were skipped because NETLIFY_NEXT_PLUGIN_SKIP is set

We can debug this if it's not triggering. Thanks!

**Comment by essenmitsosse** [comment]
Interestingly it doesn't. Heres my whole log:

<details><summary>Deploy log</summary>
<pre>
11:14:01 PM: build-image version: 609f3bb5ff1e219c9c74b55bd78852228b5c644d (focal)
11:14:01 PM: buildbot version: 609f3bb5ff1e219c9c74b55bd78852228b5c644d
11:14:01 PM: Fetching cached dependencies
11:14:01 PM: Starting to download cache of 235.4MB
11:14:03 PM: Finished downloading cache in 1.955s
11:14:03 PM: Starting to extract cache
11:14:05 PM: Finished extracting cache in 2.111s
11:14:05 PM: Finished fetching cache in 4.116s
11:14:05 PM: Starting to prepare the repo for build
11:14:06 PM: Preparing Git Reference refs/heads/BRANCH-NAME
11:14:06 PM: Parsing package.json dependencies
11:14:07 PM: Different publish path detected, going to use the one specified in the Netlify configuration file: 'out' versus '' in the Netlify UI
11:14:07 PM: Different build command detected, going to use the one specified in the Netlify configuration file: 'next build && next export' versus '' in the Netlify UI
11:14:07 PM: Starting build script
11:14:07 PM: Installing dependencies
11:14:08 PM: Python version set to 2.7
11:14:08 PM: Started restoring cached Node.js version
11:14:09 PM: Finished restoring cached Node.js version
11:14:09 PM: Attempting Node.js version '18' from .nvmrc
11:14:09 PM: v18.15.0 is already installed.
11:14:09 PM: Now using node v18.15.0 (npm v9.5.0)
11:14:09 PM: Enabling Node.js Corepack
11:14:09 PM: Started restoring cached build plugins
11:14:09 PM: Finished restoring cached build plugins
11:14:10 PM: Attempting Ruby version 2.7.2, read from environment
11:14:10 PM: Using Ruby version 2.7.2
11:14:10 PM: Using PHP version 8.0
11:14:10 PM: Started restoring cached corepack dependencies
11:14:10 PM: Finished restoring cached corepack dependencies
11:14:10 PM: No npm workspaces detected
11:14:10 PM: Started restoring cached node modules
11:14:10 PM: Finished restoring cached node modules
11:14:11 PM: Installing npm packages using npm version 9.5.0
11:14:12 PM: up to date, audited 274 packages in 461ms
11:14:12 PM: 103 packages are looking for funding
11:14:12 PM:   run `npm fund` for details
11:14:12 PM: found 0 vulnerabilities
11:14:12 PM: npm packages installed
11:14:12 PM: Started restoring cached go cache
11:14:12 PM: Finished restoring cached go cache
11:14:12 PM: Installing Go version 1.16.5 (requested 1.16.5)
11:14:16 PM: go version go1.16.5 linux/amd64
11:14:16 PM: Detected 1 framework(s)
11:14:16 PM: "next" at version "13.2.3"
11:14:16 PM: Section completed: initializing
11:14:18 PM: ​
11:14:18 PM:   Netlify Build                                                 
11:14:18 PM: ────────────────────────────────────────────────────────────────
11:14:18 PM: ​
11:14:18 PM: ❯ Version
11:14:18 PM:   @netlify/build 29.6.8
11:14:18 PM: ​
11:14:18 PM: ❯ Flags
11:14:18 PM:   baseRelDir: true
11:14:18 PM:   buildId: 64124327a330c6000898920f
11:14:18 PM:   deployId: 64124327a330c60008989211
11:14:18 PM: ​
11:14:18 PM: ❯ Current directory
11:14:18 PM:   /opt/build/repo
11:14:18 PM: ​
11:14:18 PM: ❯ Config file
11:14:18 PM:   /opt/build/repo/netlify.toml
11:14:18 PM: ​
11:14:18 PM: ❯ Context
11:14:18 PM:   branch-deploy
11:14:18 PM: ​
11:14:18 PM: ❯ Using Next.js Runtime - v4.32.2
11:14:20 PM: ​
11:14:20 PM:   1. @netlify/plugin-nextjs (onPreBuild event)                  
11:14:20 PM: ────────────────────────────────────────────────────────────────
11:14:20 PM: ​
11:14:20 PM: Next.js cache restored.
11:14:20 PM: Not running Next Runtime
11:14:20 PM: ​
11:14:20 PM: (@netlify/plugin-nextjs onPreBuild completed in 46ms)
11:14:20 PM: ​
11:14:20 PM:   2. build.command from netlify.toml                            
11:14:20 PM: ────────────────────────────────────────────────────────────────
11:14:20 PM: ​
11:14:20 PM: $ next build && next export
11:14:20 PM: info  - Skipping validation of types
11:14:20 PM: info  - Skipping linting
11:14:21 PM: info  - Creating an optimized production build...
11:14:23 PM: info  - Compiled successfully
11:14:23 PM: info  - Collecting page data...
11:14:23 PM: info  - Generating static pages (0/3)
11:14:24 PM: info  - Generating static pages (3/3)
11:14:24 PM: info  - Finalizing page optimization...
11:14:24 PM: Route (pages)                              Size     First Load JS
11:14:24 PM: ┌ ○ /                                      4.6 kB         77.8 kB
11:14:24 PM: ├   └ css/50901216b76e581e.css             1.87 kB
11:14:24 PM: ├   /_app                                  0 B            73.2 kB
11:14:24 PM: ├ ○ /404                                   182 B          73.4 kB
11:14:24 PM: └ λ /api/hello                             0 B            73.2 kB
11:14:24 PM: + First Load JS shared by all              73.9 kB
11:14:24 PM:   ├ chunks/framework-2c79e2a64abdb08b.js   45.2 kB
11:14:24 PM:   ├ chunks/main-b05cd08c4a1aceb2.js        27 kB
11:14:24 PM:   ├ chunks/pages/_app-799179ebe672fcb1.js  297 B
11:14:24 PM:   ├ chunks/webpack-8fa1640cc84ba8fe.js     750 B
11:14:24 PM:   └ css/876d048b5dab7c28.css               706 B
11:14:24 PM: λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
11:14:24 PM: ○  (Static)  automatically rendered as static HTML (uses no initial props)
11:14:25 PM: info  - using build directory: /opt/build/repo/.next
11:14:25 PM: info  - Copying "static build" directory
11:14:25 PM: info  - No "exportPathMap" found in "/opt/build/repo/next.config.js". Generating map from "./pages"
11:14:25 PM: info  - Launching 31 workers
11:14:25 PM: warn  - Statically exporting a Next.js application via `next export` disables API routes and middleware.
11:14:25 PM: This command is meant for static-only hosts, and is not necessary to make your application static.
11:14:25 PM: Pages in your application without server-side data dependencies will be automatically statically exported by `next build`, including pages powered by `getStaticProps`.
11:14:25 PM: Learn more: https://nextjs.org/docs/messages/api-routes-static-export
11:14:25 PM: info  - Exporting (0/3)
11:14:25 PM: info  - Copying "public" directory
11:14:25 PM: info  - Exporting (3/3)
11:14:26 PM: Export successful. Files written to /opt/build/repo/out
11:14:26 PM: ​
11:14:26 PM: (build.command completed in 5.6s)
11:14:26 PM: ​
11:14:26 PM:   3. @netlify/plugin-nextjs (onBuild event)                     
11:14:26 PM: ────────────────────────────────────────────────────────────────
11:14:26 PM: ​
11:14:26 PM: ​
11:14:26 PM: Starting post processing
11:14:26 PM: (@netlify/plugin-nextjs onBuild completed in 10ms)
11:14:26 PM: ​
11:14:26 PM:   4. @netlify/plugin-nextjs (onPostBuild event)                 
11:14:26 PM: ────────────────────────────────────────────────────────────────
11:14:26 PM: ​
11:14:26 PM: Post processing - HTML
11:14:26 PM: Next.js cache saved.
11:14:26 PM: ​
11:14:26 PM: (@netlify/plugin-nextjs onPostBuild completed in 41ms)
11:14:26 PM: ​
11:14:26 PM: Post processing - header rules
11:14:26 PM:   5. Deploy site                                                
11:14:26 PM: ────────────────────────────────────────────────────────────────
11:14:26 PM: ​
11:14:26 PM: Post processing - redirect rules
11:14:26 PM: Starting to deploy site from 'out'
11:14:26 PM: Calculating files to upload
11:14:26 PM: 2 new files to upload
11:14:27 PM: Post processing done
11:14:26 PM: 0 new functions to upload
11:14:26 PM: Section completed: deploying
11:14:26 PM: Site deploy was successfully initiated
11:14:27 PM: Section completed: postprocessing
11:14:26 PM: ​
11:14:26 PM: (Deploy site completed in 209ms)
11:14:26 PM: ​
11:14:26 PM:   Netlify Build Complete                                        
11:14:26 PM: ────────────────────────────────────────────────────────────────
11:14:26 PM: ​
11:14:26 PM: (Netlify Build completed in 7.5s)
11:14:26 PM: Caching artifacts
11:14:26 PM: Started saving node modules
11:14:26 PM: Finished saving node modules
11:14:26 PM: Started saving build plugins
11:14:26 PM: Finished saving build plugins
11:14:26 PM: Started saving corepack cache
11:14:27 PM: Site is live ✨
11:14:26 PM: Finished saving corepack cache
11:14:26 PM: Started saving pip cache
11:14:26 PM: Finished saving pip cache
11:14:26 PM: Started saving emacs cask dependencies
11:14:26 PM: Finished saving emacs cask dependencies
11:14:26 PM: Started saving maven dependencies
11:14:26 PM: Finished saving maven dependencies
11:14:26 PM: Started saving boot dependencies
11:14:26 PM: Finished saving boot dependencies
11:14:26 PM: Started saving rust rustup cache
11:14:26 PM: Finished saving rust rustup cache
11:14:26 PM: Started saving go dependencies
11:14:26 PM: Finished saving go dependencies
11:14:26 PM: Build script success
11:14:26 PM: Section completed: building
11:14:28 PM: Uploading Cache of size 235.5MB
11:14:30 PM: Section completed: cleanup
11:14:30 PM: Finished processing build request in 28.43s
</pre>
</details>

**Comment by essenmitsosse** [comment]
> Looking at the code, we should be warning you that NETLIFY_NEXT_PLUGIN_SKIP was set here:
>
> https://github.com/netlify/next-runtime/blob/main/packages/runtime/src/index.ts#L206-L216
>
> You should see a warning in the post-build step:
>
> > Next cache was stored, but all other functions were skipped because NETLIFY_NEXT_PLUGIN_SKIP is set

I just looked at that code, and I can't really figure out why I am not seeing this output — which might actually be a separate bug. I am going to do some more digging.

But I think it wouldn't hurt also to add a similar message here: [`index.ts:onBuild`](https://github.com/netlify/next-runtime/blob/5c0524cdc578d807b76898e455d17c1328b5b94e/packages/runtime/src/index.ts#L75-L77).

**Comment by LekoArts** [comment]
For what it's worth, you're seeing this log though:

https://github.com/netlify/next-runtime/blob/c2797e82efda953720b9e4a5d5c4c57dfafa1e0a/packages/runtime/src/index.ts#L52

**Comment by LekoArts** [comment]
That's from the "Deploy log" according to you, but you should also have a "Deploy summary" above that.
https://docs.netlify.com/site-deploys/overview/#deploy-summary

**Comment by joebentaylor1995** [comment]
Im also experiencing this issue where none of my sites are now building on netlify regardless or the environment variable being set in Netlify.

**Comment by serhalp** [comment]
Hi @essenmitsosse 

The team at Netlify have now released the new `v5` Next.js runtime which has support for both pages and app router, on-demand and time-based revalidation, automatic fine-grained cache control, and automatic image optimization using Netlify's image CDN.

You can find the documentation and additional information on the new runtime here: [Next.js on Netlify](https://docs.netlify.com/frameworks/next-js/overview/)

The `v4` runtime is now in the maintenance support phase with no new features being added. Occasional bug fixes and security patches will be applied when needed.

Thanks!

**Comment by serhalp** [comment]
@joebentaylor1995 It sounds like you're describing a different issue. Please open a new issue or use our [support forums](https://answers.netlify.com/). Keep in mind we've released v5 of the runtime which works with Next.js 13.5+.
