### ISSUE TITLE
Enable stricter typing for tests

### ISSUE THREAD

**Issue by nickytonline** [netlify/next-runtime#2028]
## Description

We ran into some issues in some tests where an object did not have the correct property. The testing setup seems to allow implicit `any`s at the moment which is why this wasn't caught.

Making types stricter for testing will help avoid potential issues like this.

_Originally posted by @nickytonline in https://github.com/netlify/next-runtime/pull/2019#discussion_r1156451846_

**Comment by sarahetter** [comment]
Can maybe be done as part of https://github.com/netlify/pod-ecosystem-frameworks/issues/428

**Comment by MarcL** [comment]
Closing this as we're creating the new minimal runtime.
