### ISSUE TITLE
[Bug]: NextJs localeDetection not working properly

### ISSUE THREAD

**Issue by benjamin-fleet** [netlify/next-runtime#2034]
### Summary

We are deploying our NextJs site to Netlify with the `@netlify/plugin-nextjs` plugin.

However the language detection & redirection does not work.

Our next-i18n.config :

```
const locizeOptions = {
  projectId: process.env.NEXT_PUBLIC_LOCIZE_PROJECTID,
  apiKey: process.env.NEXT_PUBLIC_LOCIZE_APIKEY, // to not add the api-key in production, used for saveMissing feature
  version: process.env.NEXT_PUBLIC_LOCIZE_VERSION,
  referenceLng: process.env.NEXT_PUBLIC_LOCIZE_REFLNG,
};
const LocizeLastused = require("locize-lastused");
const LocizeBackend = require("i18next-locize-backend/cjs");

const isDev = process.env.NODE_ENV === "development";
const i18nUsedPlugins = [LocizeBackend];

if (isDev) {
  // locize-lastused
  // sets a timestamp of last access on every translation segment on locize
  // -> safely remove the ones not being touched for weeks/months
  // https://github.com/locize/locize-lastused
  i18nUsedPlugins.push(LocizeLastused);
}
module.exports = {
  i18n: {
    defaultLocale: "fr",
    locales: ["fr", "es-ES", "en", "de"],
    localeDetection: true,
  },
  backend: locizeOptions,
  locizeLastUsed: {
    ...locizeOptions,
    debounceSubmit: 90000,
    allowedHosts: ["localhost"],
  },
  use: i18nUsedPlugins,
  ns: ["website_common", "website_generalities", "website_daas", "website_advantages", "website_RGPD"], // the namespaces needs to be listed here, to make sure they got preloaded
  defaultNS: "website_common",
  nsSeparator: false, // so it accepts colons
  serializeConfig: false, // because of the custom use i18next plugin
  debug: isDev,
  saveMissing: isDev, // do not saveMissing to true for production
  reloadOnPrerender: true,
};

```

May be related to https://github.com/netlify/next-runtime/issues/1876 ?

Others seem to have the same issue : https://stackoverflow.com/questions/70249769/nextjs-localedetection-not-working-when-deployed-to-netlify

Thank you in advance.

### Steps to reproduce

1. Change your browser language to English/Spanish/German
2. Go to https://fleet.co
3. Site is loaded in French

Redirection to browser language is properly done in our dev environment and in our previous Vercel hosting.

### Next Runtime version

3.8.0

### Is your issue related to the `app` directory (beta)?

- [ ] Yes, I am using the `app` directory

### More information about your build

- [ ] I am building using the CLI
- [X] I am building using file-based configuration (`netlify.toml`)

### What OS are you using?

None

### Your netlify.toml file

```
[build]
  publish = "out"

[[redirects]]
  from = "/spaces/"
  to = "/?utm_source=spaces&utm_campaign=flyer_2022"

[[redirects]]
  from = "/wework/"
  to = "/?utm_source=spaces&utm_campaign=flyer_2022"

[[redirects]]
  from = "/catalog/"
  to = "/catalog/category"

[[redirects]]
  from = "/location-ordinateurs/catalogue/"
  to = "/catalog/category"

[[redirects]]
  from = "/support/:article/"
  to = "/blog/:article/"

[[redirects]]
  from = "/location-ordinateurs/:brand/"
  to = "/catalog/brand/:brand"

[[redirects]]
  from = "/*"
  to = "/404"

[context.deploy-preview]
  command = "NEXT_PUBLIC_PR_NUMBER=$REVIEW_ID CI= yarn build"
```

### Your public/_redirects file

/* /index.html 200

### Your `next.config.js` file

```
const withPlugins = require("next-compose-plugins");
const withPWA = require("next-pwa");
const path = require("path");
const { i18n } = require("./next-i18n.config");
const generateSiteMap = require("./utils/generateSitemap");

module.exports = withPlugins(
  [
    [
      withPWA,
      {
        target: "serverless",
        pwa: {
          dest: "public",
          publicExcludes: ["!Fleet-CGV.pdf", "!images/*"],
          buildExcludes: [/images\/.*$/, /videos\/.*$/],
        },
      },
    ],
  ],
  // for translation
  {
    i18n,
    compiler: {
      styledComponents: true,
    },
    async redirects() {
      return [
        // ! Temporary redirects : Marketing campaign Flyers Oct 2022
        {
          source: "/spaces/",
          destination: "/?utm_source=spaces&utm_campaign=flyer_2022",
          permanent: false,
        },
        {
          source: "/wework/",
          destination: "/?utm_source=wework&utm_campaign=flyer_2022",
          permanent: false,
        },
        // New catalog
        {
          source: "/catalog/",
          destination: "/catalog/category",
          permanent: true,
        },
        {
          source: "/location-ordinateurs/catalogue/",
          destination: "/catalog/category",
          permanent: true,
        },
        {
          source: "/location-ordinateurs/:brand/",
          destination: "/catalog/brand/:brand",
          permanent: true,
        },

        // redirection blog
        {
          source: "/support/levee-de-fonds-ou-auto-financement-partage-experience-payfit-fleet/",
          destination: "/support/levee-de-fonds-ou-auto-financement-conseils-payfit-fleet/",
          permanent: true,
        },
      ];
    },

    webpack(config, { isServer }) {
      config.resolve.alias.images = path.join(__dirname, "public/images");

      if (isServer) {
        console.log("========>> Generating New Sitemap....");
        generateSiteMap();
      }

      return config;
    },
    trailingSlash: true,
    images: {
      domains: ["fleet.fra1.digitaloceanspaces.com", "fleet-test.fra1.digitaloceanspaces.com", "images.ctfassets.net"],
    },
  },
);

```

**Comment by LekoArts** [comment]
Hi, thanks for the issue!

Please explain this in more detail:

> However the language detection & redirection does not work.

I'm not following what you expect to see/happen in contrast to the current behavior. Thanks!

**Comment by benjamin-fleet** [comment]
Hello,

I am talking about the Nextjs Locale Detection feature :
https://nextjs.org/docs/advanced-features/i18n-routing#automatic-locale-detection

> When a user visits the application root (generally /), Next.js will try to automatically detect which locale the user prefers based on the [Accept-Language](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Language) header and the current domain.
> 
> If a locale other than the default locale is detected, the user will be redirected to either:
> 
> When using Sub-path Routing: The locale prefixed path
> When using Domain Routing: The domain with that locale specified as the default
> When using Domain Routing, if a user with the Accept-Language header fr;q=0.9 visits example.com, they will be redirected to example.fr since that domain handles the fr locale by default.
> 
> When using Sub-path Routing, the user would be redirected to /fr.

So I am expecting to be redirected to the correct subpath based on my `Accept-language` HTTP header via a 307.

On my local env : 
<img width="739" alt="Screenshot 2023-04-18 at 18 55 27" src="https://user-images.githubusercontent.com/80911898/232849727-287612e8-5288-4ede-a9e4-12380051c62a.png">


On Netlify : 
<img width="539" alt="Screenshot 2023-04-18 at 18 54 45" src="https://user-images.githubusercontent.com/80911898/232849771-b5f29546-0c27-4700-8e92-8f5db5203960.png">

**Comment by serhalp** [comment]
Hi @benjamin-fleet 

The team at Netlify have now released the new `v5` Next.js runtime which has support for both pages and app router, on-demand and time-based revalidation, automatic fine-grained cache control, and automatic image optimization using Netlify's image CDN.

You can find the documentation and additional information on the new runtime here: [Next.js on Netlify](https://docs.netlify.com/frameworks/next-js/overview/)

The `v4` runtime is now in the maintenance support phase with no new features being added. Occasional bug fixes and security patches will be applied when needed.

Thanks!
