### ISSUE TITLE
Add shim for Buffer

### ISSUE THREAD

**Issue by orinokai** [netlify/next-runtime#2047]
Next.js [13.3.1-canary.8](https://www.npmjs.com/package/next/v/13.3.1-canary.8) introduces a [change to the fetch handling](https://github.com/vercel/next.js/pull/48365/files#diff-4c54e369ddb9a2db1eed95fe1d678f94c8e82c540204475d42c78e49bf4f223aR245) that uses the global Buffer object. This causes a runtime error because Buffer is not available in Deno.

@Skn0tt has commented on the PR, but until this is fixed (or assuming it won't be) we should implement a workaround by adding Buffer to [our shims](https://github.com/netlify/next-runtime/blob/main/packages/runtime/src/templates/edge/shims.js).

**Comment by Skn0tt** [comment]
> Next.js [13.3.1-canary.8](https://www.npmjs.com/package/next/v/13.3.1-canary.8) introduces a [change to the fetch handling](https://github.com/vercel/next.js/pull/48365/files#diff-4c54e369ddb9a2db1eed95fe1d678f94c8e82c540204475d42c78e49bf4f223aR245) that uses the global Buffer object. This causes a runtime error because Buffer is not available in Deno.

It doesn't use the global Buffer object, but `require("node:buffer")`. So if we shim something, we'll have to shim `require` - which sounds even worse than shimming `globalThis.Buffer` ...

**Comment by ascorbic** [comment]
This is a lovely new feature from Turbopack https://github.com/vercel/turbo/pull/4368
