### ISSUE TITLE
Clarify using `netlify dev` when importing `@netlify/next` in docs

### ISSUE THREAD

**Issue by sarahetter** [netlify/next-runtime#2081]
Related: https://github.com/netlify/next-runtime/issues/2003

User is getting an error if they run `next dev` when using our advanced middleware - we should make it clear in the documentation for `@netlify/next` that you must run `netlify dev` and not `next dev` because of the edge function.

**Comment by MarcL** [comment]
Should we move this to https://github.com/netlify/docs now @sarahetter?
We moved to the docs site as being the source of truth for the Next runtime.
Or should this be in the README?

**Comment by nickytonline** [comment]
I think the general advice should be always run `netlify dev`. Usually people run `next dev` to compare regular Next development mode and Netlify development mode if they run into issues.

**Comment by sarahetter** [comment]
> Should we move this to https://github.com/netlify/docs now @sarahetter? We moved to the docs site as being the source of truth for the Next runtime. Or should this be in the README?

This isn't for the runtime, it's for the `next` package - our advanced middleware

**Comment by MarcL** [comment]
Ok - The docs for the `next` package also [point to the docs site](https://github.com/netlify/next-runtime/blob/main/packages/next/README.md?plain=1#L30) from the README.
It feels like that should still be the source of truth.

**Comment by serhalp** [comment]
Superseded by v5. Please feel free to reopen if this is still valid.
