### ISSUE TITLE
remove headless option of cypress workflows

### ISSUE THREAD

**Issue by danez** [netlify/next-runtime#2086]
The `headless `option of `cypress-io/github-action` does not exist anymore in the v5 version and is the new default: https://github.com/cypress-io/github-action/pull/409/files#diff-1243c5424efaaa19bd8e813c5e6f6da46316e63761421b3e5f5c8ced9a36e6b6

So it can be removed. :)

Ref: #2061 

I noticed this because I have this vscode extension that adds autocomplete and validation of github workflows.
https://github.com/github/vscode-github-actions

**Comment by LekoArts** [comment]
This was already done in https://github.com/netlify/next-runtime/pull/2069
