### ISSUE TITLE
Consolidate `getApiHandler` and `getHandler`

### ISSUE THREAD

**Issue by Skn0tt** [netlify/next-runtime#2102]
In https://github.com/netlify/next-runtime/pull/2058#discussion_r1190913344_, @pieh noted that our implementations for `getApiHandler` and `getHandler` are moving closer together. We should try to refactor things, so that we can maintain one handler implementation for both usecases.

**Comment by MarcL** [comment]
Closing this as it's superseded by the `v5` runtime work.
