### ISSUE TITLE
[Bug]: Streaming from edge function works, but chunks arrive together at once at the end

### ISSUE THREAD

**Issue by webpro** [netlify/next-runtime#2128]
### Summary

- Edge function in `pages/api/*.ts` works technically, but is not _really_ streaming
- Next.js application without any Netlify-specific configuration
- On Vercel, things work as expected, e.g. headers are set properly, etc.
- On Netlify, it works, but there is a bug or a missing piece to make streaming work end-to-end

This issue template is killing me. Just wanted to ask whether this is a known limitation/issue? Trying to fill out the fields as requested. Happy to provide more details!

I'm pointing to the reproduction repository I'm working with, but it's not really a repro since you would need API keys etc. so it's just to get an idea of what I'm working on.

(By the way, can't debug this locally properly, since `netlify dev` eventually results in `self is not defined` coming from the streaming edge function (this does not happen using `next dev`; it also happens using `netlify dev --live`); not sure how to go about this. I expected Next.js didn't use Webpack anymore, but it does and somehow `netlify` is different from `next` here.)

### A link to a reproduction repository

https://github.com/kadena-community/7-docs-demo/blob/main/src/pages/api/completion.ts

### Expected Result

See a streaming response with the first chunk coming in early on and then chunks arriving over time subsequently

### Actual Result

Technically a streaming response, but the first and last chunk are one millisecond apart

### Steps to reproduce

To see the issue right away:

1. Visit https://thunderous-medovik-731432.netlify.app
2. Select "Need suggestions?" and pick one
3. See that the response takes some time and is printed at once
4. See in the network tab that the response was indeed streaming, but all chunks arrive at the same time (see screenshots)

To get something going locally:

1. Create a Next.js application
2. Add a API function like `pages/api/my-function.js`
3. Call OpenAI's `/chat/completions` function and set `stream: true`
4. See that the response takes some time and is printed at once
5. See in the network tab that the response was indeed streaming, but all chunks arrive at the same time (see screenshots)

<img width="1037" alt="Screenshot 2023-05-19 at 12 47 31 PM" src="https://github.com/netlify/next-runtime/assets/456426/478f7a1f-8d60-4776-875a-a035fa270833">
<img width="976" alt="Screenshot 2023-05-19 at 12 47 22 PM" src="https://github.com/netlify/next-runtime/assets/456426/ee210100-9d04-4f89-b915-6da4ad892b05">

### Next Runtime version

4.36.1

### Is your issue related to the `app` directory?

- [ ] Yes, I am using the `app` directory

### More information about your build

- [ ] I am building using the CLI
- [ ] I am building using file-based configuration (`netlify.toml`)

### What OS are you using?

None

### Your netlify.toml file

<details>
  <summary>`netlify.toml`</summary>

```toml
# Paste content of your `netlify.toml` file here
```

</details>

### Your public/_redirects file

<details>
  <summary>`_redirects`</summary>

```
# Paste content of your `_redirects` file here
```

</details>

### Your `next.config.js` file

<details>
  <summary>`next.config.js`</summary>

```js
# Paste content of your `next.config.js` file here. Check there is no private info in there.
```

</details>

### Builds logs (or link to your logs)

<details>
  <summary>Build logs</summary>

```
# Paste logs here
```

</details>

### Function logs

<details>
  <summary>Function logs</summary>

```
# Paste logs here
```

</details>

### .next JSON files

<details>
  <summary>generated .next JSON files</summary>

```
# Paste file contents here. Please check there isn't any private info in them
# You can either build locally, or download the deploy from Netlify by clicking the arrow next to the deploy time.
```

</details>

**Comment by serhalp** [comment]
Hi @webpro 

The team at Netlify have now released the new `v5` Next.js runtime which has support for both pages and app router, on-demand and time-based revalidation, automatic fine-grained cache control, and automatic image optimization using Netlify's image CDN.

You can find the documentation and additional information on the new runtime here: [Next.js on Netlify](https://docs.netlify.com/frameworks/next-js/overview/)

The `v4` runtime is now in the maintenance support phase with no new features being added. Occasional bug fixes and security patches will be applied when needed.

Thanks!
