### ISSUE TITLE
[Bug]: When using `MiddlewareRequest`, trailing slash redirects stop working

### ISSUE THREAD

**Issue by ryanwalters** [netlify/next-runtime#2139]
### Summary

The use of `MiddlewareRequest` seems to be causing trailing slash redirects to stop working in some configurations.

I was able to narrow down the configuration for our application to a pretty minimal working and not working example:

The next.config.js used for both working and not working configurations:
```typescript
/** @type {import('next').NextConfig} */
const nextConfig = {
  basePath: '/money',
};

module.exports = nextConfig;
```

**Working** middleware.ts:
```typescript
import { type NextRequest } from 'next/server';
import { type MiddlewareResponse } from '@netlify/next';
import { NextResponse } from 'next/server';

type NextRequestCustom = Omit<NextRequest, 'geo'> & { geo: any };

export async function middleware(nextRequest: NextRequestCustom): Promise<MiddlewareResponse | NextResponse> {
  return NextResponse.next();
}
```

**Not working** middleware.ts:
```typescript
import { type NextRequest } from 'next/server';
import { MiddlewareRequest, type MiddlewareResponse } from '@netlify/next';
import { NextResponse } from 'next/server';

type NextRequestCustom = Omit<NextRequest, 'geo'> & { geo: any };

export async function middleware(nextRequest: NextRequestCustom): Promise<MiddlewareResponse | NextResponse> {
  const request = new MiddlewareRequest(nextRequest);
  const response = await request.next();

  return response;
}
```

### A link to a reproduction repository

https://github.com/ryanwalters/middleware-repro

### Expected Result

Url redirects to https://main--thriving-puffpuff-af3b3e.netlify.app/money (no trailing slash)

### Actual Result

Url returns a 500 error with the message, Invalid URL: '/money'

Please compare against https://www.britannica.com/money/ which behaves as expected, automatically redirecting to /money without a trailing slash. The only difference between these two branches is that middleware is enabled. The issue is easy to reproduce, but here is an x-nf-request-id just in case you guys need it for debugging purposes: 01H1AA394CRGYR298SB24ATAT8

### Steps to reproduce

1. Navigate to https://main--thriving-puffpuff-af3b3e.netlify.app/money/

### Next Runtime version

- next@13.4.4
- @netlify/next@1.4.7
- @netlify/plugin-nextjs@4.38.0

### Is your issue related to the `app` directory?

- [ ] Yes, I am using the `app` directory

### More information about your build

- [ ] I am building using the CLI
- [X] I am building using file-based configuration (`netlify.toml`)

### What OS are you using?

None

### Your netlify.toml file

<details>
  <summary>`netlify.toml`</summary>

```toml
[build]
    command = "npm run build"
    publish = ".next"
```

</details>

### Your public/_redirects file

<details>
  <summary>`_redirects`</summary>

```
# No redirects file
```

</details>

### Your `next.config.js` file

<details>
  <summary>`next.config.js`</summary>

```js
/** @type {import('next').NextConfig} */
const nextConfig = {
  basePath: '/money',
};

module.exports = nextConfig;
```

</details>

### Builds logs (or link to your logs)

<details>
  <summary>Build logs</summary>

```
https://app.netlify.com/sites/thriving-puffpuff-af3b3e/deploys/649350ecedd5790b64b0589e
```

</details>

### Function logs

<details>
  <summary>Function logs</summary>

```
# Paste logs here
```

</details>

### .next JSON files

<details>
  <summary>generated .next JSON files</summary>

```
# Paste file contents here. Please check there isn't any private info in them
# You can either build locally, or download the deploy from Netlify by clicking the arrow next to the deploy time.
```

</details>

**Comment by taty2010** [comment]
Hi, @ryanwalters I used the info you provided above, and as you mentioned it doesn't seem like we can reproduce the error on our end. Can you let us know what version of Next you are using? 

I will look into this more with the team, but we will most likely need more information to be able to reproduce the issue and try to resolve it.

**Comment by ryanwalters** [comment]
@taty2010 I was able to pare down our app enough to be a pretty bare-bones repro repo: https://github.com/ryanwalters/middleware-repro

This is currently deployed as https://main--thriving-puffpuff-af3b3e.netlify.app/money/

**Comment by p0wl** [comment]
hey, we see the same issue on "next": "12.3.4", and "@netlify/plugin-nextjs": "4.40.1",. Any idea or workaround known?

**Comment by p0wl** [comment]
this is what we see in the logs. I'm trying to find where this comes from, but I can't spot it. I found this place: https://github.com/netlify/next-runtime/blob/main/packages/runtime/src/templates/edge-shared/next-utils.ts#L129, but I don't think that is the right place. Where is this "new NextUrl" called? Within the nextjs package?

<img width="1023" alt="image" src="https://github.com/netlify/next-runtime/assets/596578/e6e0e63c-31c2-43c3-83d3-3826039d08b0">

**Comment by p0wl** [comment]
@taty2010 did you manage to find something with your team? We still see this issue
