### ISSUE TITLE
[Bug]: Redirects not working in monorepo

### ISSUE THREAD

**Issue by kluplau** [netlify/next-runtime#2169]
### Summary

I have a monorepo with 2 Netlify websites built using NextJS.
Each of them with their own `netlify.toml`-file in their folder.
I have redirects defined in `next.config.mjs` and it works locally.

[The readme states that I need to configure the `publish` to be the full path of the `.next` folder.](https://github.com/netlify/next-runtime#monorepos)
It's defined with the full path `apps/web/.next` in Netlify UI and the plugin doesn't break, but it also doesn't work.
When I try to define full paths in the `toml`-files, then it uses the path relatively, which repeats the path, and the plugin throws because the folder `apps/web/apps/web/.next` doesn't exist, obviously.

There are no errors or warnings, it just doesn't work.

### A link to a reproduction repository

NONE

### Expected Result

Expected it to redirect as it does locally

### Actual Result

It gives 404

### Steps to reproduce

1. Create a nextjs monorepo
2. Add redirects to the `next.config.js`
4. Verify it works locally
5. Deploy to Netlify and define publish path there
6. Verify that redirects doesn't work on Netlify

### Next Runtime version

4.38.0

### Is your issue related to the `app` directory?

- [ ] Yes, I am using the `app` directory

### More information about your build

- [ ] I am building using the CLI
- [X] I am building using file-based configuration (`netlify.toml`)

### What OS are you using?

Mac OS

### Your netlify.toml file

<details>
  <summary>apps/web/netlify.toml</summary>

```toml
[template]
  incoming-hooks = ["Sanity"]

[build]
  ignore = "/bin/false"

[[plugins]]
  package = "@netlify/plugin-nextjs"
```
</details>

### Your `next.config.js` file

<details>
<summary>apps/web/next.config.mjs</summary>

```javascript
import {DEFAULT_LOCALE, LOCALES} from "@repo/consts/web.mjs";
import * as sanityClient from "@lagobe/core/lib/sanity.client.mjs";

/** @type {import("next").NextConfig} */
const config = {
  // @TODO turn swcMinify back on once the agressive dead code elimination bug that casues
  // `ReferenceError: FieldPresenceWithOverlay is not defined` is fixed
  swcMinify: false,
  i18n: {
    locales: LOCALES,
    defaultLocale: DEFAULT_LOCALE,
    localeDetection: false,
  },
  images: {
    remotePatterns: [
      { hostname: "cdn.sanity.io" },
      { hostname: "source.unsplash.com" },
    ],
  },
  eslint: {
    /// Set this to false if you want production builds to abort if there's lint errors
    ignoreDuringBuilds: process.env.VERCEL_ENV === "production",
  },
  transpilePackages: ["@repo/core", "@repo/consts"],
  async redirects() {
    return await sanityClient.getRedirects();
  },
  trailingSlash: true,
  experimental: {
    scrollRestoration: true,
  },
};

export default config;

```

</details>

**Comment by serhalp** [comment]
Hi @kluplau 

The team at Netlify have now released the new `v5` Next.js runtime which has support for both pages and app router, on-demand and time-based revalidation, automatic fine-grained cache control, and automatic image optimization using Netlify's image CDN.

You can find the documentation and additional information on the new runtime here: [Next.js on Netlify](https://docs.netlify.com/frameworks/next-js/overview/)

The `v4` runtime is now in the maintenance support phase with no new features being added. Occasional bug fixes and security patches will be applied when needed.

Thanks!
