### ISSUE TITLE
[Bug]: Cannot access x-forwarded-host in getServerSideProps

### ISSUE THREAD

**Issue by brightonmike** [netlify/next-runtime#2223]
### Summary

Locally, including when using `netlify dev` I can use `x-forwarded-host` header.

But once deployed, it's not populated. In fact, I can't find a way to access the hostname within `getServerSideProps` at all.

I'm looking to trigger a function from a page route, and just can't see how to achieve this.

### A link to a reproduction repository

https://github.com/on-associates/on-nextjs-template

### Expected Result

x-forwarded-host returns site hostname

### Actual Result

x-forwarded-host is not populated

### Steps to reproduce

1. Attempt to access `context?.req?.headers['x-forwarded-host']` within `getServerSideProps`

### Next Runtime version

4.39.1

### Is your issue related to the `app` directory?

- [ ] Yes, I am using the `app` directory

### More information about your build

- [X] I am building using the CLI
- [X] I am building using file-based configuration (`netlify.toml`)

### What OS are you using?

Mac OS

### Your netlify.toml file

[build]
command = "yarn build:prod"
publish = ".next"

[dev]
functions = "functions"

[build.environment]
YARN_FLAGS = "--network-timeout 1000000"

[[plugins]]
package = "@netlify/plugin-nextjs"
[[plugins]]
package = "@netlify/plugin-functions-install-core"

# [build]
# command = "yarn vendors:storybook:build"
# publish = "storybook-static/"

### Your public/_redirects file

<details>
  <summary>`_redirects`</summary>

```
# Paste content of your `_redirects` file here
```

</details>

### Your `next.config.js` file

<details>
  <summary>`next.config.js`</summary>

```js
# Paste content of your `next.config.js` file here. Check there is no private info in there.
```

</details>

### Builds logs (or link to your logs)

<details>
  <summary>Build logs</summary>

```
# Paste logs here
```

</details>

### Function logs

<details>
  <summary>Function logs</summary>

```
# Paste logs here
```

</details>

### .next JSON files

<details>
  <summary>generated .next JSON files</summary>

```
# Paste file contents here. Please check there isn't any private info in them
# You can either build locally, or download the deploy from Netlify by clicking the arrow next to the deploy time.
```

</details>

**Comment by nickytonline** [comment]
Thanks for reporting the issue @brightonmike. I've added it to our backlog for the team to investigate.

**Comment by serhalp** [comment]
Hi @brightonmike 

The team at Netlify have now released the new `v5` Next.js runtime which has support for both pages and app router, on-demand and time-based revalidation, automatic fine-grained cache control, and automatic image optimization using Netlify's image CDN.

You can find the documentation and additional information on the new runtime here: [Next.js on Netlify](https://docs.netlify.com/frameworks/next-js/overview/)

The `v4` runtime is now in the maintenance support phase with no new features being added. Occasional bug fixes and security patches will be applied when needed.

Thanks!
