### ISSUE TITLE
[Bug]: Response is not compressed

### ISSUE THREAD

**Issue by hrishikesh-k** [netlify/next-runtime#2243]
### Summary

This was the result of a user complaint.

AWS has a response size hard-limit of 6 MB. Sending response over that size, would lead to an error page like:

![image](https://github.com/netlify/next-runtime/assets/11403551/36187320-4034-49b1-b01c-f0c7c89e9f0c)

While I agree, this is a very high response size, but users can need this. Also, the user who was having an issue, wasn't using API routes, but getting an error in SSR route. They wish to be able to send a HTML file which is more than 6 MB uncompressed, but far lesser when compressed.

### A link to a reproduction repository

[zd-165325.zip](https://github.com/netlify/next-runtime/files/13536436/zd-165325.zip)

### Expected Result

There are 2 options off the top of my head:

1. The response should either be gzip/brotli compressed within our handler. By default Next.js applies gzip, which doesn't seem to be happening here for some reason. This would have to be handled per request. Some clients might not support receiving a particular encoding.
~2. OR we should use streaming functions now that Netlify supports those, so we can stream the response to the client and won't hit this limit.~ Our docs say that limit exists there too: https://docs.netlify.com/functions/create/?fn-language=ts#response-streaming

### Actual Result

Response size goes over 6 MB, thus the Function crashed error page appears. Right now, it appears we're sending the response as-is, and allowing Netlify CDN to handle the compression. However, this can only happen after we recive the response from AWS Lambda, which doesn't happen if the size goes over 6 MB.

### Steps to reproduce

My test site is here: https://app.netlify.com/sites/zd-165325/deploys
The error is visible on `/api/hello` page.

If you check my first deploy: https://64cd3e980a9545000882e70d--zd-165325.netlify.app/api/hello, it fails. It's using Next.js' default option for compress.

But iff you check my second deploy: https://64cd406facd4700008ddde49--zd-165325.netlify.app/api/hello, it still fails, even though I'm explicitly asking Next.js to compress the response based on my `next.config.js`.

When checking in browser locally, I can see a transfer size of 2 MB with the default settings:

![image](https://github.com/netlify/next-runtime/assets/11403551/4b904e64-0a56-4d6a-aab1-bf2b97426ffe)

So, a 6.7 MB response can be brought down to 2 MB if it's compressed.

### Next Runtime version

4.39.2

### Is your issue related to the `app` directory?

- [ ] Yes, I am using the `app` directory

### More information about your build

- [ ] I am building using the CLI
- [ ] I am building using file-based configuration (`netlify.toml`)

### What OS are you using?

Linux

**Comment by Hrishikesh-K** [comment]
None, and very likely nothing would happen in the coming next weeks. There are other pieces of work happening with the Runtime.

**Comment by StreetGUY32** [comment]
@hrishikesh-k  still no update on this?

**Comment by hrishikesh-k** [comment]
Have you tried using Next.js Runtime v5? If not, you can opt-in to that to see if it makes a difference.

**Comment by serhalp** [comment]
Closing as stale. Please feel free to reopen if this is still an issue with the v5 release. Thanks!
