### ISSUE TITLE
Modify demo site configurations to enable improved monorepo support on Netlify

### ISSUE THREAD

**Issue by nickytonline** [netlify/next-runtime#2258]
We've [rolled out improved monorepo support on Netlify](https://www.netlify.com/blog/better-monorepos-on-netlify/). Bring the Next.js runtime repository in line with these improvements.

All configuration paths will need to be relative to the monorepo root.

**Comment by MarcL** [comment]
The team at Netlify have now released the new `v5` Next.js runtime which has support for both pages and app router, on-demand and time-based revalidation, automatic fine-grained cache control, and automatic image optimization using Netlify's image CDN.

You can find the documentation and additional information on the `v5` runtime here: [Next.js on Netlify](https://docs.netlify.com/frameworks/next-js/overview/)

The `v4` runtime is now in the maintenance support phase, with no new features being added. Occasional bug fixes and security patches will be applied when needed.

Thanks!!

The team at Netlify have now released the new `v5` Next.js runtime which has support for both pages and app router, on-demand and time-based revalidation, automatic fine-grained cache control, improved monorepo support, and automatic image optimization using Netlify's image CDN.

You can find the documentation and additional information on the `v5` runtime here: [Next.js on Netlify](https://docs.netlify.com/frameworks/next-js/overview/)

The `v4` runtime is now in the maintenance support phase, with no new features being added. Occasional bug fixes and security patches will be applied when needed.

Thanks!
