### ISSUE TITLE
[Bug]: searchParams and userSearchParams not working as expected

### ISSUE THREAD

**Issue by belafonte** [netlify/next-runtime#2273]
### Summary

I noticed, that searchParams in a page are returned as string instead of an array as described here:
https://nextjs.org/docs/app/api-reference/file-conventions/page#searchparams-optional

should be:
`/shop?a=1&a=2 | { a: ['1', '2'] }`

current:
`/shop?a=1&a=2 | { a: '1, 2' }`

also it seams the the useSearchParams has some issues with its functions.
For instance toString() does not translate the & correctly but creates ,+ instead of an &.
Maybe has to to with the issue above.

I'am using nextjs 13.4.9 because of some 500 errors. 
But should be irrelevant to the issue.

### A link to a reproduction repository

none

### Expected Result

searchParams as array

### Actual Result

result is an string

### Steps to reproduce

add multiple searchParams to page

check searchParams

### Next Runtime version

4.0.0

### Is your issue related to the `app` directory?

- [X] Yes, I am using the `app` directory

### More information about your build

- [ ] I am building using the CLI
- [X] I am building using file-based configuration (`netlify.toml`)

### What OS are you using?

Mac OS

### Your netlify.toml file

<details>
  <summary>`netlify.toml`</summary>

```toml
# Paste content of your `netlify.toml` file here
```

</details>

### Your public/_redirects file

<details>
  <summary>`_redirects`</summary>

```
# Paste content of your `_redirects` file here
```

</details>

### Your `next.config.js` file

<details>
  <summary>`next.config.js`</summary>

```js
# Paste content of your `next.config.js` file here. Check there is no private info in there.
```

</details>

### Builds logs (or link to your logs)

<details>
  <summary>Build logs</summary>

```
# Paste logs here
```

</details>

### Function logs

<details>
  <summary>Function logs</summary>

```
# Paste logs here
```

</details>

### .next JSON files

<details>
  <summary>generated .next JSON files</summary>

```
# Paste file contents here. Please check there isn't any private info in them
# You can either build locally, or download the deploy from Netlify by clicking the arrow next to the deploy time.
```

</details>

**Comment by serhalp** [comment]
Hi @belafonte 

The team at Netlify have now released the new `v5` Next.js runtime which has support for both pages and app router, on-demand and time-based revalidation, automatic fine-grained cache control, and automatic image optimization using Netlify's image CDN.

You can find the documentation and additional information on the new runtime here: [Next.js on Netlify](https://docs.netlify.com/frameworks/next-js/overview/)

The `v4` runtime is now in the maintenance support phase with no new features being added. Occasional bug fixes and security patches will be applied when needed.

Thanks!
