### ISSUE TITLE
[Bug]: `Error: Cannot find module 'next/dist/server/future/route-modules/pages/vendored/contexts/amp-context'` in NextJS preview mode

### ISSUE THREAD

**Issue by ben221199** [netlify/next-runtime#2329]
### Summary

Website is working normally, but when setting NextJS in preview mode to see live Sanity data, Netlify gives a 500 error. Locally, the preview mode works. Also, in a Docker image it works as expected. Netlify is the only place where preview mode fails.

### A link to a reproduction repository

Private repository

### Expected Result

No error, just NextJS on Netlify in preview mode getting live data from Sanity.

### Actual Result

A 500 error in the browser and the error log below.

### Steps to reproduce

Don't know.

### Next Runtime version

4.40.3-rc.0

### Is your issue related to the `app` directory?

- [ ] Yes, I am using the `app` directory

### More information about your build

- [ ] I am building using the CLI
- [X] I am building using file-based configuration (`netlify.toml`)

### What OS are you using?

None

### Your netlify.toml file

<details>
  <summary>`netlify.toml`</summary>

```toml
[[plugins]]
    package = "@netlify/plugin-nextjs"

[[plugins]]
    package = "@netlify/plugin-sitemap"

    [plugins.inputs]
    exclude = [
        '.next/404.html',
        '.next/404/index.html',
        '.next/500.html',
        '.next/500/index.html',
    ]
```

</details>

### Your public/_redirects file

None

### Your `next.config.js` file

<details>
  <summary>`next.config.js`</summary>

```js
/** @type {import('next').NextConfig} */
module.exports = {
    i18n: {
        defaultLocale: 'nl',
        locales: ['nl'],
    },
    images: {
        domains: ['cdn.sanity.io'],
    },
    output: 'standalone',
    swcMinify: false,

    async redirects() {
        const sanityRedirects = await fetchSanityRedirects();
        return sanityRedirects;
    },
};
```

</details>

### Builds logs (or link to your logs)

None

### Function logs

<details>
  <summary>Function logs</summary>

```js
Error: Cannot find module 'next/dist/server/future/route-modules/pages/vendored/contexts/amp-context'
Require stack:
- /var/task/node_modules/next/dist/shared/lib/head.js
- /var/task/node_modules/next/head.js
- /var/task/.next/server/pages/index.js
- /var/task/node_modules/next/dist/server/require.js
- /var/task/node_modules/next/dist/server/next-server.js
- /var/task/.netlify/functions-internal/___netlify-handler/___netlify-handler.js
- /var/task/___netlify-handler.js
- /var/runtime/index.mjs
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at /var/task/node_modules/next/dist/server/require-hook.js:54:36
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at mod.require (/var/task/node_modules/next/dist/server/require-hook.js:62:32)
    at require (node:internal/modules/cjs/helpers:121:18)
    at Object.<anonymous> (/var/task/node_modules/next/dist/shared/lib/head.js:29:34)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/var/task/node_modules/next/dist/shared/lib/head.js',
    '/var/task/node_modules/next/head.js',
    '/var/task/.next/server/pages/index.js',
    '/var/task/node_modules/next/dist/server/require.js',
    '/var/task/node_modules/next/dist/server/next-server.js',
    '/var/task/.netlify/functions-internal/___netlify-handler/___netlify-handler.js',
    '/var/task/___netlify-handler.js',
    '/var/runtime/index.mjs'
  ]
}
```

</details>

### .next JSON files

None

**Comment by ben221199** [comment]
It seems that it will fail when `next/head` is imported during preview mode.

**Comment by popmatik** [comment]
I'm also getting the error when deployed to Vercel. 

This is not whilst using preview mode, just standard browsing of the site.

**Comment by pcastr0** [comment]
@bkochendorfer thanks! this works! will use this version for now..

**Comment by DanielBiegler** [comment]
Can confirm @bkochendorfer 's suggestion works. Downgrading is the way to go for now. Thank you so much!

**Comment by dsteenburgh-navan** [comment]
Having this issue on `@netlify/plugin-nextjs` version `4.37.1` + `next` version `13.5.6`.

I was able to solve this by downgrading to NextJS `13.4.12` instead. I did not try any other version combinations.

**Comment by kdmcguire** [comment]
Same problem here.

* Not working: `@netlify/plugin-nextjs@4.41.1` & `next@13.5.6`
* Working: `@netlify/plugin-nextjs@4.41.1` & `next@13.4.19`

**Comment by laurent-le-graverend** [comment]
Got the same issue here, with Next v14. Downgrading to Next v13.4.19 solves the issue for now.

**Comment by justynspooner** [comment]
We're having a similar issue and we're not using preview mode. It appears to happen on pages that use `getServerSideProps` and `import Head from 'next/head';`

Not working: @netlify/plugin-nextjs@4.41.1 & next@13.5.6
Working: @netlify/plugin-nextjs@4.41.1 & next@13.4.8

```
ERROR Error: Cannot find module 'next/dist/server/future/route-modules/pages/vendored/contexts/head-manager-context'
```

We have just upgraded to 13 and still use the /pages router if that makes a difference.

**Comment by niall-byrne** [comment]
Also seeing this error on next15 with pages routing:

```
Runtime.UnhandledPromiseRejection: Error: Cannot find module 'next/dist/server/future/route-modules/pages/vendored/contexts/amp-context'
```

**Comment by eliasm307** [comment]
Im having the same issue

**Comment by kai-CuroWork** [comment]
Same issue here

**Comment by eliasm307** [comment]
> Got the same issue here, with Next v14. Downgrading to Next v13.4.19 solves the issue for now.

This worked for me

**Comment by cdking007** [comment]
Downgrading to Next v13.4.19 solves the issue for me also.

**Comment by shortcircuit3** [comment]
I had this issue and the only way I could solve it was to move from netlify to vercel :(

**Comment by kylekirkby** [comment]
Any idea what is going on here? @Skn0tt

**Comment by digeverything** [comment]
I am having a similar error, previewing with Prismic on a NextJS site.

```
Nov 17, 02:19:27 PM: f4700146 ERROR   ⨯ Error: Cannot find module 'next/dist/server/future/route-modules/pages/vendored/contexts/head-manager-context'
Require stack:
- /var/task/node_modules/next/dist/client/script.js
- /var/task/node_modules/next/script.js
- /var/task/node_modules/@prismicio/next/dist/PrismicPreview.cjs
- /var/task/node_modules/@prismicio/next/dist/index.cjs
- /var/task/apps/web/.next/server/pages/api/preview.js
- /var/task/node_modules/next/dist/server/future/helpers/module-loader/node-module-loader.js
- /var/task/node_modules/next/dist/server/future/helpers/module-loader/route-module-loader.js
- /var/task/node_modules/next/dist/server/next-server.js
- /var/task/apps/web/.netlify/functions-internal/___netlify-handler/___netlify-handler.js
- /var/task/___netlify-handler.js
- /var/runtime/index.mjs
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at /var/task/node_modules/next/dist/server/require-hook.js:54:36
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at mod.require (/var/task/node_modules/next/dist/server/require-hook.js:62:32)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/var/task/node_modules/next/dist/client/script.js:33:42)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/var/task/node_modules/next/dist/client/script.js',
    '/var/task/node_modules/next/script.js',
    '/var/task/node_modules/@prismicio/next/dist/PrismicPreview.cjs',
    '/var/task/node_modules/@prismicio/next/dist/index.cjs',
    '/var/task/apps/web/.next/server/pages/api/preview.js',
    '/var/task/node_modules/next/dist/server/future/helpers/module-loader/node-module-loader.js',
    '/var/task/node_modules/next/dist/server/future/helpers/module-loader/route-module-loader.js',
    '/var/task/node_modules/next/dist/server/next-server.js',
    '/var/task/apps/web/.netlify/functions-internal/___netlify-handler/___netlify-handler.js',
    '/var/task/___netlify-handler.js',
    '/var/runtime/index.mjs'
  ]
}
```

`"@netlify/plugin-nextjs": "^4.41.2"`
`"next": "^14.0.3",`

Fixed it by downgrading to `"next": "^13.4.19",`

**Comment by ericpias** [comment]
I am also seeing a similar deploy only issue on pages that use getServerSideProps and import Head from 'next/head' and add metadata.  500 error.  Using page routing and NextJS 14.0.2.  Downgrading back to 13.4.8 is a work-around for me.  For some reason 13.4.19 did not resolve it for me.

**Comment by kdmcguire** [comment]
Hey folks, there's a related discussion going on in Netlify's support forum here: https://answers.netlify.com/t/next-js-14-upgrade-results-in-500-status-code/105786/4

In essence, it sounds like they _might_ be working on an overhaul of how Next.js runs on Netlify* and they'd rather focus on that than keep playing whack-a-mole with the current system, as the rate of Next.js updates encountering problems on Netlify is increasing.

*I can't say that for sure, I don't work there, but that's what I inferred from the responses.

**Comment by smyja** [comment]
same error for "next": "^13.4.6"

**Comment by dimitrisnl** [comment]
Since most messages are from November, I wanted to mention that it's still an issue. I upgraded to Next 14 and pages with getServerSideProps, broke with the same error.

I see that the issue has been open for 2 months now. I don't mind Vercel making things hard for other providers, but I would like some confirmation or estimate from Netlify.

**Comment by vdavid** [comment]
The bug is still present today. Next 14.0.4. Didn't find a solution.

**Comment by patrickhladun** [comment]
I have a similar issue when deployed to Netlify; locally work fine?

I am trying different versions of the next 13 but have had no luck so far.

Some have issue with `amp-context` module  my one with `head-manager-context` module

```
Jan 17, 01:39:03 PM: d43a33f1 ERROR  Error: Cannot find module 'next/dist/server/future/route-modules/pages/vendored/contexts/head-manager-context'
Require stack:
- /var/task/node_modules/next/dist/client/script.js
- /var/task/node_modules/next/dist/shared/lib/router/router.js
- /var/task/node_modules/next/dist/client/router.js
- /var/task/node_modules/next/router.js
- /var/task/node_modules/nextjs-progressbar/dist/index.js
- /var/task/.next/server/pages/_app.js
- /var/task/node_modules/next/dist/server/require.js
- /var/task/node_modules/next/dist/server/next-server.js
- /var/task/.netlify/functions-internal/___netlify-odb-handler/___netlify-odb-handler.js
- /var/task/___netlify-odb-handler.js
- /var/runtime/index.mjs
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at /var/task/node_modules/next/dist/server/require-hook.js:54:36
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at mod.require (/var/task/node_modules/next/dist/server/require-hook.js:62:32)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/var/task/node_modules/next/dist/client/script.js:33:42)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/var/task/node_modules/next/dist/client/script.js',
    '/var/task/node_modules/next/dist/shared/lib/router/router.js',
    '/var/task/node_modules/next/dist/client/router.js',
    '/var/task/node_modules/next/router.js',
    '/var/task/node_modules/nextjs-progressbar/dist/index.js',
    '/var/task/.next/server/pages/_app.js',
    '/var/task/node_modules/next/dist/server/require.js',
    '/var/task/node_modules/next/dist/server/next-server.js',
    '/var/task/.netlify/functions-internal/___netlify-odb-handler/___netlify-odb-handler.js',
    '/var/task/___netlify-odb-handler.js',
    '/var/runtime/index.mjs'
  ]
}
```

**Comment by roman-yakobnyuk** [comment]
Same issue when trying to build using output: `standard` for any project that uses new `@next/third-party` script.

Get the following error on startup:
```
 Cannot find module 'next/dist/server/future/route-modules/pages/vendored/contexts/head-manager-context'
 ```

**Comment by patrickhladun** [comment]
I found a solution to my problem, and I want to share it with you in case it can help.

In my situation, downgrading nextjs to the previous version didn't solve the issue. So, I started to investigate my code. During this process, I was removing third-party code from the _app.js file and discovered that the culprit was the [nextjs-progressbar](https://www.npmjs.com/package/nextjs-progressbar) package.

I hope this information is useful to someone.

> I have a similar issue when deployed to Netlify; locally work fine?
> 
> I am trying different versions of the next 13 but have had no luck so far.
> 
> Some have issue with `amp-context` module my one with `head-manager-context` module
> 
> ```
> Jan 17, 01:39:03 PM: d43a33f1 ERROR  Error: Cannot find module 'next/dist/server/future/route-modules/pages/vendored/contexts/head-manager-context'
> Require stack:
> - /var/task/node_modules/next/dist/client/script.js
> - /var/task/node_modules/next/dist/shared/lib/router/router.js
> - /var/task/node_modules/next/dist/client/router.js
> - /var/task/node_modules/next/router.js
> - /var/task/node_modules/nextjs-progressbar/dist/index.js
> - /var/task/.next/server/pages/_app.js
> - /var/task/node_modules/next/dist/server/require.js
> - /var/task/node_modules/next/dist/server/next-server.js
> - /var/task/.netlify/functions-internal/___netlify-odb-handler/___netlify-odb-handler.js
> - /var/task/___netlify-odb-handler.js
> - /var/runtime/index.mjs
>     at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
>     at /var/task/node_modules/next/dist/server/require-hook.js:54:36
>     at Module._load (node:internal/modules/cjs/loader:922:27)
>     at Module.require (node:internal/modules/cjs/loader:1143:19)
>     at mod.require (/var/task/node_modules/next/dist/server/require-hook.js:62:32)
>     at require (node:internal/modules/cjs/helpers:119:18)
>     at Object.<anonymous> (/var/task/node_modules/next/dist/client/script.js:33:42)
>     at Module._compile (node:internal/modules/cjs/loader:1256:14)
>     at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
>     at Module.load (node:internal/modules/cjs/loader:1119:32) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>     '/var/task/node_modules/next/dist/client/script.js',
>     '/var/task/node_modules/next/dist/shared/lib/router/router.js',
>     '/var/task/node_modules/next/dist/client/router.js',
>     '/var/task/node_modules/next/router.js',
>     '/var/task/node_modules/nextjs-progressbar/dist/index.js',
>     '/var/task/.next/server/pages/_app.js',
>     '/var/task/node_modules/next/dist/server/require.js',
>     '/var/task/node_modules/next/dist/server/next-server.js',
>     '/var/task/.netlify/functions-internal/___netlify-odb-handler/___netlify-odb-handler.js',
>     '/var/task/___netlify-odb-handler.js',
>     '/var/runtime/index.mjs'
>   ]
> }
> ```

**Comment by popmatik** [comment]
Just to add. I resolved this issue on Vercel by disabling build cache and redeploying.

**Comment by martinnabhan** [comment]
Hey everyone. `amp-context` and `head-manager-context` are imported dynamically by `next/head`, which means they won't be properly included in the Netlify function. We can force them to be added by using `netlify.toml`:
```tool
[functions]
  included_files = [
  "node_modules/next/dist/server/future/route-modules/pages/vendored/contexts/amp-context*",
  "node_modules/next/dist/server/future/route-modules/pages/vendored/contexts/head-manager-context*",
]
```
This solved the issue for me.

**Comment by oskarhertzman** [comment]
> Hey everyone. `amp-context` and `head-manager-context` are imported dynamically by `next/head`, which means they won't be properly included in the Netlify function. We can force them to be added by using `netlify.toml`:
> 
> ```shell
> [functions]
>   included_files = [
>   "node_modules/next/dist/server/future/route-modules/pages/vendored/contexts/amp-context*",
>   "node_modules/next/dist/server/future/route-modules/pages/vendored/contexts/head-manager-context*",
> ]
> ```
> 
> This solved the issue for me.

Thanks this worked!

**Comment by nolafs** [comment]
Hi,

I tried to include the files but it is not working. I am wondering if this has to do with my nx monorepro. Anybody using NX repro and using include_files?

**Comment by martinnabhan** [comment]
You need to add the correct path to `includes_files`. Since you're using a monorepo I guess you have multiple `node_modules` folders, so you have to add the path to the `node_modules` folder which contains `next`.

**Comment by ben221199** [comment]
> Hey everyone. `amp-context` and `head-manager-context` are imported dynamically by `next/head`, which means they won't be properly included in the Netlify function. We can force them to be added by using `netlify.toml`:
> 
> ```shell
> [functions]
>   included_files = [
>   "node_modules/next/dist/server/future/route-modules/pages/vendored/contexts/amp-context*",
>   "node_modules/next/dist/server/future/route-modules/pages/vendored/contexts/head-manager-context*",
> ]
> ```
> 
> This solved the issue for me.

This solved the issue for me too. However, I think this should not be the final solution, so I will wait until Netlify comes up with one.

**Comment by lpalombo** [comment]
> Hey everyone. `amp-context` and `head-manager-context` are imported dynamically by `next/head`, which means they won't be properly included in the Netlify function. We can force them to be added by using `netlify.toml`:
> 
> ```shell
> [functions]
>   included_files = [
>   "node_modules/next/dist/server/future/route-modules/pages/vendored/contexts/amp-context*",
>   "node_modules/next/dist/server/future/route-modules/pages/vendored/contexts/head-manager-context*",
> ]
> ```
> 
> This solved the issue for me.

Just adding here that with a project using the PNPM package manager. This solution does not appear to work. Probably has something to do with it's virtual file system.

**Comment by SimonPrato11** [comment]
> Hey everyone. `amp-context` and `head-manager-context` are imported dynamically by `next/head`, which means they won't be properly included in the Netlify function. We can force them to be added by using `netlify.toml`:
> 
> ```shell
> [functions]
>   included_files = [
>   "node_modules/next/dist/server/future/route-modules/pages/vendored/contexts/amp-context*",
>   "node_modules/next/dist/server/future/route-modules/pages/vendored/contexts/head-manager-context*",
> ]
> ```
> 
> This solved the issue for me.

This solved the issue, waiting for Netlify final solution

**Comment by garvishtayal** [comment]
> I encountered the same issue and was able to work around this for now by downgrading and pinning my application to `"next": "13.4.8"`.

Worked for me too changing Next dependency to older version

**Comment by dannytlake** [comment]
We are experiencing this issue, running:
- pnpm
- Next.js @ ^13.4.6
- @netlify/plugin-nextjs @ ^4.41.3

Netlify SSR logs for the deploy preview show error 
`Mar 5, 11:40:14 AM: 97c86c80 ERROR  Error: Cannot find module 'next/dist/server/future/route-modules/pages/vendored/contexts/amp-context'`

See https://github.com/composable-com/composable-ui/pull/31 for more details

**Comment by kuji2336** [comment]
> ERROR  Error: Cannot find module 'next/dist/server/future/route-modules/pages/vendored/contexts/head-manager-context'

did u find a solution?

**Comment by kuji2336** [comment]
> I found a solution to my problem, and I want to share it with you in case it can help.
> 
> In my situation, downgrading nextjs to the previous version didn't solve the issue. So, I started to investigate my code. During this process, I was removing third-party code from the _app.js file and discovered that the culprit was the [nextjs-progressbar](https://www.npmjs.com/package/nextjs-progressbar) package.
> 
> I hope this information is useful to someone.
> 
> > I have a similar issue when deployed to Netlify; locally work fine?
> > I am trying different versions of the next 13 but have had no luck so far.
> > Some have issue with `amp-context` module my one with `head-manager-context` module
> > ```
> > Jan 17, 01:39:03 PM: d43a33f1 ERROR  Error: Cannot find module 'next/dist/server/future/route-modules/pages/vendored/contexts/head-manager-context'
> > Require stack:
> > - /var/task/node_modules/next/dist/client/script.js
> > - /var/task/node_modules/next/dist/shared/lib/router/router.js
> > - /var/task/node_modules/next/dist/client/router.js
> > - /var/task/node_modules/next/router.js
> > - /var/task/node_modules/nextjs-progressbar/dist/index.js
> > - /var/task/.next/server/pages/_app.js
> > - /var/task/node_modules/next/dist/server/require.js
> > - /var/task/node_modules/next/dist/server/next-server.js
> > - /var/task/.netlify/functions-internal/___netlify-odb-handler/___netlify-odb-handler.js
> > - /var/task/___netlify-odb-handler.js
> > - /var/runtime/index.mjs
> >     at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
> >     at /var/task/node_modules/next/dist/server/require-hook.js:54:36
> >     at Module._load (node:internal/modules/cjs/loader:922:27)
> >     at Module.require (node:internal/modules/cjs/loader:1143:19)
> >     at mod.require (/var/task/node_modules/next/dist/server/require-hook.js:62:32)
> >     at require (node:internal/modules/cjs/helpers:119:18)
> >     at Object.<anonymous> (/var/task/node_modules/next/dist/client/script.js:33:42)
> >     at Module._compile (node:internal/modules/cjs/loader:1256:14)
> >     at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
> >     at Module.load (node:internal/modules/cjs/loader:1119:32) {
> >   code: 'MODULE_NOT_FOUND',
> >   requireStack: [
> >     '/var/task/node_modules/next/dist/client/script.js',
> >     '/var/task/node_modules/next/dist/shared/lib/router/router.js',
> >     '/var/task/node_modules/next/dist/client/router.js',
> >     '/var/task/node_modules/next/router.js',
> >     '/var/task/node_modules/nextjs-progressbar/dist/index.js',
> >     '/var/task/.next/server/pages/_app.js',
> >     '/var/task/node_modules/next/dist/server/require.js',
> >     '/var/task/node_modules/next/dist/server/next-server.js',
> >     '/var/task/.netlify/functions-internal/___netlify-odb-handler/___netlify-odb-handler.js',
> >     '/var/task/___netlify-odb-handler.js',
> >     '/var/runtime/index.mjs'
> >   ]
> > }
> > ```

did u find solution?

**Comment by kuji2336** [comment]
`@next/third-parties: 14.1.4` 
`next:14.1.0`

also can lead this error
```
⨯ Error: Cannot find module 'next/dist/server/future/route-modules/pages/vendored/contexts/head-manager-context'
Require stack:
- /var/task/node_modules/next/dist/client/script.js
- /var/task/node_modules/next/script.js
- /var/task/node_modules/@next/third-parties/dist/google/youtube-embed.js
- /var/task/node_modules/@next/third-parties/dist/google/index.js```

**Comment by kuji2336** [comment]
> Same issue when trying to build using `output: "standalone"` for any project that uses new `@next/third-parties` script.
> 
> Get the following error on startup:
> 
> ```
>  Cannot find module 'next/dist/server/future/route-modules/pages/vendored/contexts/head-manager-context'
> ```

got same error when using `@next/third-parties:^14.1.4` version, did u find a solution?

**Comment by serhalp** [comment]
Hi folks!

The team at Netlify have now released the new `v5` Next.js runtime which has support for both pages and app router, on-demand and time-based revalidation, automatic fine-grained cache control, and automatic image optimization using Netlify's image CDN.

You can find the documentation and additional information on the new runtime here: [Next.js on Netlify](https://docs.netlify.com/frameworks/next-js/overview/)

The `v4` runtime is now in the maintenance support phase with no new features being added. Occasional bug fixes and security patches will be applied when needed.

Can anyone confirm whether this issue is still occurring with v5 of the runtime and Next.js 13.5+?

**Comment by ben221199** [comment]
Well, I have to remove the fix that temporary solved this bug. I will try that tomorrow if I get the errors back or not.

**Comment by serhalp** [comment]
I'm closing this since there hasn't been any activity here in a couple months, we completely rewrote the runtime for v5, and we haven't seen reports of this issue with v5 yet.

Feel free to start a new thread on https://answers.netlify.com/ or open a new issue if you need more support. Thanks folks.

**Comment by ben221199** [comment]
I removed from `netlify.toml`:
```toml
[functions]
    included_files = [
        "node_modules/next/dist/server/future/route-modules/pages/vendored/contexts/amp-context*",
        "node_modules/next/dist/server/future/route-modules/pages/vendored/contexts/head-manager-context*",
    ]
```

And I removed from `package.json` (`dependencies`):
```json
    "@netlify/blobs": "^7.3.0",
```

It deployed without errors. The website itself also worked. In preview, one page kept showing the loading screen, so I have to look into that. I didn't face any 500 errors.
