### ISSUE TITLE
[bug]: `netlify dev` fails to run middleware

### ISSUE THREAD

**Issue by orinokai** [netlify/next-runtime#2339]
Since shipping the PR to vendor Deno dependencies, `netlify dev` no longer runs middleware or edge functions correctly.

https://github.com/netlify/next-runtime/pull/2302

To fix this, we should ensure the vendored dependencies are copied to the dev server directory during `onPreDev`

This is the build step that does the vendoring: https://github.com/netlify/next-runtime/pull/2302/files#diff-126513369bd4ea319345bbb81971f82857aecab4d597bf4e0063f7dd07082b3a

Added to Linear as FRA-53.

**Comment by serhalp** [comment]
Completed long ago by https://github.com/netlify/next-runtime/pull/2341
