### ISSUE TITLE
Cache headers returned from Middleware aren't respected

### ISSUE THREAD

**Issue by Skn0tt** [netlify/next-runtime#2350]
As reported in https://answers.netlify.com/t/cache-api-call-in-nextjs-middleware/105322, we're currently not respecting cache-control headers returned by a Next.js middleware.

This is because the edge functions that run middleware are configured to run before the cache, as opposed to after the cache.

If we want to support cache-control headers in middleware, we'll need to execute it post-cache. See https://docs.netlify.com/edge-functions/optional-configuration/#when-to-use-caching for more info on that.

**Comment by Skn0tt** [comment]
The "obvious" fix would be to set the fourth parameter to `"manual"` here: https://github.com/netlify/next-runtime/blob/2945a7a7dfd1b72067fce175c338d3a4f14d6501/packages/runtime/src/helpers/edge.ts#L429

**Comment by orinokai** [comment]
I'm intrigued about why the edge functions have `cache: manual` set [on line 467](https://github.com/netlify/next-runtime/blob/2945a7a7dfd1b72067fce175c338d3a4f14d6501/packages/runtime/src/helpers/edge.ts#L467), but the edge middleware does not
@ascorbic do you have any insight into why?

**Comment by orinokai** [comment]
oh hang on... i've just read the description above again and can see that that parameter causes the function to run after the cache and that's not what we want for middleware

**Comment by Skn0tt** [comment]
Is it, though? "running after the cache" means that they have the option to cache by configuring cache-control headers. If they don't, they'll never be cached

**Comment by orinokai** [comment]
afaik if we run after the cache then static content will take precedence - and a key benefit of middleware is being able to change headers or body content on prerendered static content, which wouldn't work if it ran after the cache

**Comment by ascorbic** [comment]
I _think_ this is the expected behaviour for Next.js, which is why I did it like that. Also, at least at the time, it was a way to ensure it ran in a separate EF deploy from functions, so we could do rewrites from middleware to an edge function endpoint

**Comment by MarcL** [comment]
Closing this as we won't be fixing in the `v4` runtime.
