### ISSUE TITLE
404 error in css and js files

### ISSUE THREAD

**Issue by sebakthapa** [netlify/next-runtime#2565]
### Next version
13.5
upgraded to 14 but still error persist

### About the error
Getting 404 error on CSS and JS files as seen in network tab. This doesn't always occur. On the same deploy it sometimes occur while other time it doesn't. Before, rebuilding had done immediate fix (didn't occur about for a day after rebuild) but now even rebuilding is not doing a immediate fix.

### Why 404?
I downloaded the build directory from Netlify and I found that when the error occurs the requested file is not in the requested path (the file doesn't exist anywhere in the build directory) BUT when it the app is working well, then the file requested is the file that is in the build directory. What is the main concern is under same build being deployed sometimes it requests the unavailable file while other time it requests the correct file.

### What I found after digging in
When I visit the deploy preview URL of Netlify it works well. But for my custom domain (lets say `domain.com`) the CSS/JS file request sent is inconsistent.
I tried pointing the domain from `domain.com` to `app.domain.com` and `test.domain.com` and it worked well there too but when I repoint to `domain.com` it again broke.
Then, hosted the next app to my server with  `domain.com` added and there it is working well.

So, is this Netlify caching issue under `domain.com`? 

### Steps to Reproduce
The error is inconsistent and can't be reproduced.

**Comment by pieh** [comment]
Hi @sebakthapa 
We are already aware of this issue and implemented changes to prevent it from happening again in the future, but are still in the process of cache purges to get out of problematic state for sites affected by it. You can force this for your sites by triggering a redeploy or following https://docs.netlify.com/platform/caching/#purge-by-site yourself as mass purge we are performing might take some time until it handle your site(s).

**Comment by sebakthapa** [comment]
Will redeploy work? 
I am asking because it has been almost a week since I first encountered this issue and I have redeployed it multiple times. Before, redeploy/rebuild fixed the problem for about a day or two but yesterday, after around ( 31 Jul 2024 09:15:00 GMT) the issue was never resolved even on rebuild.

> We are already aware of this issue and implemented changes to prevent it from happening again in the future

When was the new changes implemented?
I am afraid if purging the cache or a redeploy today would work because it wasn't working yesterday.

**Comment by sebakthapa** [comment]
No, I didn't have any redeploy after that time. I'll give it a try.
