### ISSUE TITLE
Page using preview bypasses the password protect feature

### ISSUE THREAD

**Issue by d4rekanguok** [netlify/next-runtime#682]
**Describe the bug**

Hi, we're running a NextJS + netlity/plugin-next site on Netlify with the site-wide password feature enabled. We've worked on a page that is rendered via `api/preview` route + fetching inside `getStaticProps`.

There have been reports of ppl being able to access the protected page _without_ entering the password, even though it's only the html without css / js. In one of those incidents, other pages are gated as expected (I did not experience this myself.) 

I'm not sure if it's a bug or even an issue with this plugin, but I also don't know what else could had cause this. Any ideas?

**Versions**
- Next.js: ^10.1.3
- plugin (if installed at fixed version): ^3.9.0

**If you're using file-based installation**
- netlify.toml: 
```
[build]
  command = "yarn build"
  publish = "out"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "frame-ancestors 'self' https://project-name.sanity.studio;"
```

**Comment by ascorbic** [comment]
Hi. Could you try this again with version 4.0.0 of the plugin or later and see if it is still happening?

**Comment by d4rekanguok** [comment]
Thank you for your response @ascorbic! We no longer use the password protected feature on Netlify so I won't be able to test it with the latest plugin release. Please feel free to close the issue if necessary.
