### ISSUE TITLE
Automatic support for animated webp

### ISSUE THREAD

**Issue by overlordofmu** [netlify/next-runtime#787]
### Steps to reproduce

1. Deploy site with animated Webp images using this plugin.
2. Note that the images are not animated after the site is deployed.

### A link to a reproduction repository

N/A

### More information about your build

- [ ] I am building using the CLI
- [X] I am building using file-based configuration (netlify.toml)

### Your `netlify.toml` file

```shell
The site uses the automatically generated `netlify.toml` created by the plugin.
```

### Relevant log output (or link to your logs)

The logs are private but the support team at Netlify can get them for you.

**Comment by ascorbic** [comment]
Upstream issue https://github.com/unjs/ipx/issues/53

**Comment by ascorbic** [comment]
I've renamed this because it already supports animated output, but there's currently no way of automatically enabling it.

**Comment by kriakiku** [comment]
The same goes for gifs. Please give at least an opportunity to disable netlify optimization 👉👈

**Comment by MarcL** [comment]
We now support animated `webp` images with the new image CDN using the `v5` runtime.

I'll close this issue as we won't add it to the `v4` runtime.

The `v4` runtime is now in the maintenance support phase with no new features being added. Occasional bug fixes and security patches will be applied when needed.
